import CoordinateDiagram,{type CoordinateDiagramProps as Diagram} from "./CoordinateDiagram";
const m=String.raw;
const blue="#42648b",orange="#a4513a";
const sq=(x:number)=>x*x;
export const math3IntegralApplicationFigures:Record<string,Record<number,Diagram>>={
 "m3-signed-area":{0:{title:"軸の上下で高さを変える",description:m`指定範囲は $[-1,2]$。左側の帯の高さは $-x$、右側は $x$。両方とも正の面積として足します。`,xRange:[-1.5,2.5],yRange:[-1.5,2.5],curves:[{label:m`$y=x$`,value:x=>x,from:-1,to:2}],areas:[{from:-1,to:0,upper:()=>0,lower:x=>x,label:m`左の面積 $\dfrac12$`},{from:0,to:2,upper:x=>x,lower:()=>0,label:m`右の面積 $2$`}],points:[{x:0,y:0,label:m`符号が変わる点 $(0,0)$`}]}},
 "m3-between-curves":{0:{title:"帯の高さは上から下を引く",description:m`交点の横座標は $0,1$。その間では直線が上です。破線は $x=\dfrac12$ の帯の高さを示します。`,xRange:[-0.2,1.3],yRange:[-0.2,1.3],tick:0.5,curves:[{label:m`$y=x$`,value:x=>x,from:0,to:1},{label:m`$y=x^2$`,value:sq,from:0,to:1,color:blue}],areas:[{from:0,to:1,upper:x=>x,lower:sq,label:m`高さ $x-x^2$、幅 $dx$`}],segments:[{from:[0.5,0.25],to:[0.5,0.5],dashed:true,label:m`$x=\dfrac12$ での高さは $\dfrac14$`}]}},
 "m3-area-splitting":{0:{title:"指定上端まで上下を確かめる",description:m`指定区間は $[0,2]$ です。$x=1$ より先では放物線が上になり、面積の式も逆になります。`,xRange:[-0.2,2.3],yRange:[-0.2,4.3],curves:[{label:m`$y=x$`,value:x=>x,from:0,to:2},{label:m`$y=x^2$`,value:sq,from:0,to:2,color:blue}],areas:[{from:0,to:1,upper:x=>x,lower:sq,label:m`前半の高さ $x-x^2$`},{from:1,to:2,upper:sq,lower:x=>x,label:m`後半の高さ $x^2-x$`}],points:[{x:1,y:1,label:m`上下が変わる交点 $(1,1)$`}],segments:[{from:[2,2],to:[2,4],label:m`指定上端 $x=2$`}]}},
 "m3-horizontal-area":{0:{title:"横の帯の右端と左端",description:m`縦の範囲は $-2\le y\le1$。右端は直線、左端は放物線です。破線は $y=0$ の横の帯の長さを示します。`,xRange:[-0.5,4.5],yRange:[-2.5,1.5],curves:[{label:m`$x=y^2$ の上側 $y=\sqrt x$`,value:Math.sqrt,from:0,to:1},{label:m`$x=y^2$ の下側 $y=-\sqrt x$`,value:x=>-Math.sqrt(x),from:0,to:4},{label:m`$x=2-y$`,value:x=>2-x,from:1,to:4,color:blue}],areas:[{from:0,to:1,upper:Math.sqrt,lower:x=>-Math.sqrt(x),label:"二曲線で囲まれた領域"},{from:1,to:4,upper:x=>2-x,lower:x=>-Math.sqrt(x),label:""}],points:[{x:1,y:1,label:m`交点 $(1,1)$`},{x:4,y:-2,label:m`交点 $(4,-2)$`}],segments:[{from:[0,0],to:[2,0],dashed:true,label:m`横の長さ $(2-y)-y^2$（図は $y=0$）`}]}},
 "m3-cross-section-volume":{0:{title:"断面を正面から見る",description:m`例題の $x=\dfrac12$ での断面です。一辺 $\dfrac12$ の正方形なので断面積は $\dfrac14$。この断面に、奥行き方向の薄い厚み $dx$ を掛けます。`,axisDescription:"断面内の二方向を描いています。積み重ねる方向は、この図に垂直です。",xRange:[-0.1,0.7],yRange:[-0.1,0.7],tick:0.25,areas:[{from:0,to:0.5,upper:()=>0.5,lower:()=>0,label:m`断面積 $A\left(\dfrac12\right)=\dfrac14$`}],segments:[{from:[0,0],to:[0.5,0],label:m`一辺 $x=\dfrac12$`},{from:[0.5,0],to:[0.5,0.5]},{from:[0.5,0.5],to:[0,0.5]},{from:[0,0.5],to:[0,0]}]}},
 "m3-disk-volume":{
 0:{title:"回す前の領域と半径",description:m`縦の帯を横軸のまわりに回すと円板になります。破線は $x=\dfrac14$ での半径です。`,xRange:[-0.2,1.3],yRange:[-0.2,1.3],tick:0.5,curves:[{label:m`$y=\sqrt x$`,value:Math.sqrt,from:0,to:1}],areas:[{from:0,to:1,upper:Math.sqrt,lower:()=>0,label:m`$0\le y\le\sqrt x$`}],segments:[{from:[0,0],to:[1,0],width:4,color:orange,label:m`回転軸 $y=0$`},{from:[0.25,0],to:[0.25,0.5],dashed:true,label:m`半径 $\sqrt x$（図では $\dfrac12$）`}]},
 1:{title:"回した後の円板の断面",description:m`$x=\dfrac14$ で軸に垂直に切った断面です。半径は $\dfrac12$。円板の面積は $\dfrac\pi4$ であり、半径そのものではありません。`,axisDescription:"断面を正面から見ています。中心が回転軸です。",xRange:[-0.7,0.7],yRange:[-0.7,0.7],tick:0.5,circles:[{x:0,y:0,r:0.5,label:m`断面積 $\pi(\sqrt x)^2=\pi x$`}],segments:[{from:[0,0],to:[0.5,0],label:m`半径 $\dfrac12$`}]}
 },
 "m3-washer-volume":{
 0:{title:"軸から二つの距離を測る",description:m`$x\le y\le1$ の領域を横軸のまわりに回します。外半径は $1$、内半径は $x$ です。`,xRange:[-0.2,1.3],yRange:[-0.2,1.3],tick:0.5,curves:[{label:m`$y=1$`,value:()=>1,from:0,to:1},{label:m`$y=x$`,value:x=>x,from:0,to:1,color:blue}],areas:[{from:0,to:1,upper:()=>1,lower:x=>x,label:"回す領域"}],segments:[{from:[0,0],to:[1,0],width:4,color:orange,label:"回転軸"},{from:[0.5,0],to:[0.5,1],dashed:true,label:m`外半径 $1$`},{from:[0.5,0],to:[0.5,0.5],width:4,label:m`内半径 $x$（図は $x=\dfrac12$）`}]},
 1:{title:"内側の円を除いた断面",description:m`$x=\dfrac12$ で切った円環です。内側の円の中は空いています。断面積は外の円の面積から内の円の面積を引いた $\dfrac{3\pi}{4}$ です。`,axisDescription:"断面を正面から見ています。共通の中心が回転軸です。",xRange:[-1.3,1.3],yRange:[-1.3,1.3],tick:0.5,circles:[{x:0,y:0,r:1,label:m`外半径 $1$`},{x:0,y:0,r:0.5,label:m`内半径 $\dfrac12$`,color:blue}],segments:[{from:[0,0],to:[1,0],label:m`外半径は軸から外周まで`},{from:[0,0],to:[0,0.5],color:blue,label:m`内半径は軸から内周まで`}]}
 },
 "m3-rotation-direction":{0:{title:"縦軸回転では横に切る",description:m`図の領域は $0\le y\le1$、$0\le x\le\sqrt y$。横の帯を縦軸のまわりに回すと、半径 $\sqrt y$ の円板になります。`,xRange:[-0.2,1.3],yRange:[-0.2,1.3],tick:0.5,curves:[{label:m`$y=x^2$、すなわち $x=\sqrt y$`,value:sq,from:0,to:1}],areas:[{from:0,to:1,upper:()=>1,lower:sq,label:m`$0\le y\le1$ の領域`}],segments:[{from:[0,0],to:[0,1],color:orange,width:4,label:m`回転軸 $x=0$`},{from:[0,0.25],to:[0.5,0.25],dashed:true,label:m`半径 $\sqrt y$（図は $y=\dfrac14$）`}]}},
 "m3-graph-length":{
 0:{title:"横と縦の変化を合わせる",description:m`両端は $(0,0)$ と $(4,3)$。線分の長さは三平方で $5$。積分の公式でも同じ値になることを確かめます。`,xRange:[-0.5,4.5],yRange:[-0.5,3.5],segments:[{from:[0,0],to:[4,3],width:3,label:m`曲線 $y=\dfrac34x$`},{from:[0,0],to:[4,0],dashed:true,label:m`横の変化 $4$`},{from:[4,0],to:[4,3],dashed:true,label:m`縦の変化 $3$`}]},
 1:{title:"単位円の短い円弧",description:m`横の範囲は $0\le x\le\dfrac12$。上半円のうち、縦軸から右へ進む円弧です。中心角は $\dfrac\pi6$。`,xRange:[-0.2,1.2],yRange:[-0.2,1.2],tick:0.5,arcs:[{x:0,y:0,r:1,from:Math.PI/3,to:Math.PI/2,label:m`$y=\sqrt{1-x^2}$ の指定部分`}],points:[{x:0,y:1,label:m`$(0,1)$`},{x:0.5,y:Math.sqrt(3)/2,label:m`$\left(\dfrac12,\dfrac{\sqrt3}{2}\right)$`}],segments:[{from:[0,0],to:[0,1],dashed:true},{from:[0,0],to:[0.5,Math.sqrt(3)/2],dashed:true}]}
 },
 "m3-parametric-length":{0:{title:"一度だけたどる四分円",description:m`$t$ が $0$ から $\dfrac\pi2$ へ増えると、右端から上端へ反時計回りに進みます。横と縦の変化から求めた速さは $1$ です。`,xRange:[-0.2,1.2],yRange:[-0.2,1.2],tick:0.5,arcs:[{x:0,y:0,r:1,from:0,to:Math.PI/2,label:m`$(x,y)=(\cos t,\sin t)$`}],points:[{x:1,y:0,label:m`出発 $t=0$`},{x:0,y:1,label:m`到着 $t=\dfrac\pi2$`}]}},
 "m3-parametric-area":{0:{title:"横の幅は媒介変数の幅と違う",description:m`$x=t^2$、$y=t$ は $y=\sqrt x$ の曲線を右向きに一度たどります。高さは $t$、横の幅は $dx=2t\,dt$ です。`,xRange:[-0.2,1.3],yRange:[-0.2,1.3],tick:0.5,curves:[{label:m`$y=\sqrt x$`,value:Math.sqrt,from:0,to:1}],areas:[{from:0,to:1,upper:Math.sqrt,lower:()=>0,label:m`面積は $\int_0^1t\cdot2t\,dt$`}],points:[{x:0,y:0,label:m`出発 $t=0$`},{x:1,y:1,label:m`到着 $t=1$`}]}},
 "m3-displacement-distance":{1:{title:"速度の負の部分も道のりに加える",description:m`時刻 $1$ で進む向きが変わります。速度のグラフと横軸の間の二つの面積は各 $\dfrac12$。変位では相殺し、道のりでは加えます。`,axisDescription:m`横軸は時刻 $t$（秒）、縦軸は速度 $v$（メートル毎秒）。`,xRange:[-0.2,2.3],yRange:[-1.3,1.3],curves:[{label:m`$v=t-1$`,value:t=>t-1,from:0,to:2}],areas:[{from:0,to:1,upper:()=>0,lower:t=>t-1,label:m`負向きに進む道のり $\dfrac12$ メートル`},{from:1,to:2,upper:t=>t-1,lower:()=>0,label:m`正向きに進む道のり $\dfrac12$ メートル`}],points:[{x:1,y:0,label:m`折り返す時刻 $t=1$`}]}}
};
export default function Math3IntegralApplicationDiagrams({slug,index}:{slug:string;index:number}){
 const figure=math3IntegralApplicationFigures[slug]?.[index];
 return figure?<CoordinateDiagram {...figure}/>:null;
}
