"use client";
import CoordinateDiagram,{type CoordinateDiagramProps as Diagram} from "./CoordinateDiagram";
const blue="#42648b";
const parabola=(h:number,k:number,a=1)=>({label:`$y=${a===1?"":a===-1?"-":a}(x${h<0?"+"+(-h):"-"+h})^2${k<0?k:"+"+k}$`,value:(x:number)=>a*(x-h)**2+k});
function vertexFigure(h:number,k:number,a:number,title:string):Diagram{return {title,description:"頂点と、軸から左右に同じ距離の点を確かめます。",xRange:[h-3,h+3],yRange:[Math.min(k,k+a)-2,Math.max(k,k+4*a)+2],curves:[parabola(h,k,a)],points:[{x:h,y:k,label:`頂点 $(${h},${k})$`},{x:h-1,y:k+a,label:`$(${h-1},${k+a})$`},{x:h+1,y:k+a,label:`$(${h+1},${k+a})$`}],segments:[{from:[h,Math.min(k,k+a)-2],to:[h,Math.max(k,k+4*a)+2],dashed:true,label:`軸 $x=${h}$`}]};}
function intervalFigure(l:number,r:number):Diagram{return {title:"使える部分だけで値を比べる",description:`$y=(x-1)^2$ の $${l}\\le x\\le${r}$ の部分です。描いた曲線の部分だけで値を比べます。`,xRange:[-1,4],yRange:[-1,6],curves:[{label:`$y=(x-1)^2$、$${l}\\le x\\le${r}$`,value:x=>(x-1)**2,from:l,to:r}],points:[{x:l,y:(l-1)**2,label:`左端 $(${l},${(l-1)**2})$`},{x:r,y:(r-1)**2,label:`右端 $(${r},${(r-1)**2})$`},...(l<1?[{x:1,y:0,label:"頂点 $(1,0)$"}]:[])],segments:[{from:[1,-1],to:[1,6],dashed:true,label:"軸 $x=1$"}]};}
export const mathOneQuadraticFigures:Record<string,(Diagram|undefined)[]>={
 "m1-graph-points":[{title:"横座標から高さを確かめる",description:"横座標が同じでも、高さが式と一致する点だけがグラフ上です。",xRange:[-3,3],yRange:[-1,7],curves:[{label:"$y=x^2+1$",value:x=>x*x+1}],points:[{x:2,y:5,label:"$(2,5)$ はグラフ上"},{x:2,y:4,label:"$(2,4)$ はグラフ上ではない"}]}],
 "m1-domain-range":[{title:"指定された三つの入力だけ",description:"入力は $-1,0,1$ だけ。間を線で結ばず、値域は $\\{0,1\\}$ です。",xRange:[-2,2],yRange:[-1,2],points:[{x:-1,y:1,label:"$(-1,1)$"},{x:0,y:0,label:"$(0,0)$"},{x:1,y:1,label:"$(1,1)$"}]},{title:"区間のすべての入力",description:"$0\\le x\\le2$ の入力から $1\\le y\\le5$ の出力が得られます。両端を含む線分です。",xRange:[-1,3],yRange:[-1,6],curves:[{label:"$y=2x+1$、$0\\le x\\le2$",value:x=>2*x+1,from:0,to:2}],points:[{x:0,y:1,label:"左端 $(0,1)$"},{x:2,y:5,label:"右端 $(2,5)$"}]}],
 "m1-basic-parabola":[{title:"頂点と左右対称",description:"$x=1$ と $x=-1$ で高さは同じです。",xRange:[-3,3],yRange:[-1,5],curves:[{label:"$y=x^2$",value:x=>x*x}],points:[{x:0,y:0,label:"頂点 $(0,0)$"},{x:1,y:1,label:"$(1,1)$"},{x:-1,y:1,label:"$(-1,1)$"}]},{title:"同じ縮尺で開き方を比べる",description:"$x=1$ で高さはそれぞれ $1,2$。同じ高さでは、係数が大きい方が縦の軸に近くなります。",xRange:[-3,3],yRange:[-1,5],curves:[{label:"実線：$y=x^2$",value:x=>x*x},{label:"破線：$y=2x^2$",value:x=>2*x*x,color:blue,dashed:true}],points:[{x:1,y:1,label:"$y=x^2$ の $(1,1)$"},{x:1,y:2,label:"$y=2x^2$ の $(1,2)$"}]}],
 "m1-parabola-translation":[{title:"点の座標には移動量を足す",description:"点 $(1,1)$ を右へ $2$、上へ $1$ 移すと $(3,2)$。線分は移動前後の対応を表します。",xRange:[-1,5],yRange:[-1,5],points:[{x:1,y:1,label:"移動前 $(1,1)$"},{x:3,y:2,label:"移動後 $(3,2)$"}],segments:[{from:[1,1],to:[3,1],dashed:true,label:"横へ $2$"},{from:[3,1],to:[3,2],dashed:true,label:"縦へ $1$"}]},{title:"放物線全体を同じだけ移す",description:"頂点 $(0,0)$ は $(2,1)$ へ。新しい横座標から $2$ を引くと、移動前の横座標に戻ります。",xRange:[-2,5],yRange:[-1,6],curves:[{label:"破線：移動前 $y=x^2$",value:x=>x*x,color:blue,dashed:true},{label:"実線：移動後 $y=(x-2)^2+1$",value:x=>(x-2)**2+1}],points:[{x:0,y:0,label:"移動前の頂点 $(0,0)$"},{x:2,y:1,label:"移動後の頂点 $(2,1)$"}]}],
 "m1-quadratic-graph":[vertexFigure(1,-3,2,"頂点と二つの確認点"),vertexFigure(-2,1,1,"平方完成で頂点の位置を読む")],
 "m1-parabola-extrema":[vertexFigure(2,1,1,"最小値と、それをとる入力"),vertexFigure(-2,1,1,"平方完成後の最小値")],
 "m1-interval-extrema":[intervalFigure(0,3),intervalFigure(2,3)],
 "m1-equation-graph":[{title:"解は共有点の横座標",description:"$y=0$ になる二点の横座標が方程式の解です。",xRange:[-3,4],yRange:[-3,5],curves:[{label:"$y=x^2-x-2$",value:x=>x*x-x-2}],points:[{x:-1,y:0,label:"$(-1,0)$"},{x:2,y:0,label:"$(2,0)$"}]},vertexFigure(1,0,1,"重解なら一点で接する")],
 "m1-quadratic-inequality":[{title:"関数値が負になる入力を選ぶ",description:"$x^2-x-2<0$ の解は $-1<x<2$。零点は厳密不等号の解に含みません。",xRange:[-3,4],yRange:[-4,6],curves:[{label:"$y=x^2-x-2$",value:x=>x*x-x-2}],points:[{x:-1,y:0,label:"左の零点 $(-1,0)$"},{x:2,y:0,label:"右の零点 $(2,0)$"}]},{title:"開く向きが変わると符号も変わる",description:"$-x^2+x+2>0$ の解は $-1<x<2$。上に凸なので内側で $x$ 軸より上です。",xRange:[-3,4],yRange:[-6,4],curves:[{label:"$y=-x^2+x+2$",value:x=>-x*x+x+2}],points:[{x:-1,y:0,label:"$(-1,0)$"},{x:2,y:0,label:"$(2,0)$"}]}],
 "m1-quadratic-inequality-boundaries":[vertexFigure(1,0,1,"零点以外では正"),vertexFigure(0,1,1,"零点がなくても常に正")],
 "m1-graph-intersections":[{title:"同じ横座標で二つの高さが一致",description:"二曲線を同時に満たす点が共有点です。",xRange:[-3,4],yRange:[-1,6],curves:[{label:"実線：$y=x^2$",value:x=>x*x},{label:"破線：$y=x+2$",value:x=>x+2,color:blue,dashed:true}],points:[{x:-1,y:1,label:"$(-1,1)$"},{x:2,y:4,label:"$(2,4)$"}]}],
 "m1-quadratic-model":[undefined,{title:"辺の長さと面積",description:"$0<x<6$ で $S=-(x-3)^2+9$。両端は長方形にならず、頂点では面積 $9$ を実際にとれます。",axisDescription:"横軸は辺の長さ $x$（センチメートル）、縦軸は面積 $S$（平方センチメートル）。",xRange:[-1,7],yRange:[-1,10],curves:[{label:"$S=-(x-3)^2+9$、$0<x<6$",value:x=>9-(x-3)**2,from:0,to:6}],points:[{x:0,y:0,open:true,label:"$x=0$ は含まない"},{x:6,y:0,open:true,label:"$x=6$ は含まない"},{x:3,y:9,label:"最大面積 $9$、一辺 $3$"}]}],
};
export default function MathOneQuadraticDiagrams({slug,index}:{slug:string;index:number}){const figure=mathOneQuadraticFigures[slug]?.[index];return figure?<CoordinateDiagram {...figure}/>:null;}
