import {J,S,m,q,ns,finish} from "./junior-authoring";
import {equationExtraBanks,squareCondition,generalQuadratic} from "./junior-equation-extra";
const chapter="方程式と平方根の基礎",sec=["等式と方程式","平方根と二次方程式"];
const equation=(n:number,fraction=false)=>q(fraction?m`$\frac{x}3+1=${n+1}$ を解きなさい。`:m`$2x+3=${2*n+3}$ を解きなさい。`,m`$x=${fraction?3*n:n}$。`,"両辺に同じ操作をし、文字だけを残します。",fraction?m`両辺から $1$ を引き $\frac x3=${n}$。両辺を $3$ 倍して $x=${3*n}$。元の左辺は $${n}+1=${n+1}$。`:m`両辺から $3$ を引き $2x=${2*n}$。両辺を $2$ で割り $x=${n}$。代入すると両辺が一致します。`);
const simultaneous=(n:number,sub=false)=>q(sub?m`$y=2x,\ x+y=${3*n}$ を連立して解きなさい。`:m`$x+y=${n+2},\ x-y=${n-2}$ を連立して解きなさい。`,sub?m`$x=${n},y=${2*n}$。`:m`$x=${n},y=2$。`,sub?"一方の式で表した文字を、もう一方へ代入します。":"二式を足すと、消える文字があります。",sub?m`$x+2x=${3*n}$ より $x=${n}$。$y=2x=${2*n}$。両方の式で確かめます。`:m`足すと $2x=${2*n}$。$x=${n}$ を戻すと $y=2$。両方の式を満たす一組です。`);
const roots=(n:number,both=false)=>q(both?m`$${n*n}$ の平方根をすべて答えなさい。`:m`$\sqrt{${n*n}}$ の値を求めなさい。`,both?m`$${n}$ と $-${n}$。`:m`$${n}$。`,both?"二乗して指定の数になる数を、正負とも考えます。":"根号は非負の平方根一つを表します。",m`$(${n})^2=(-${n})^2=${n*n}$。`+(both?"したがって正負二つです。":m`$\sqrt{${n*n}}$ はそのうち非負の $${n}$ です。`));
const quadratic=(n:number,factored=false)=>q(factored?m`$(x-${n})(x+2)=0$ を解きなさい。`:m`$x^2=${n*n}$ を解きなさい。`,factored?m`$x=${n},-2$。`:m`$x=\pm${n}$。`,factored?"積が零なら、少なくとも一方の因数が零です。":"二乗して同じ値になる正負二つを考えます。",factored?m`$x-${n}=0$ または $x+2=0$。どちらの値も元の積を零にします。因数で割ると解を落とすことがあります。`:m`$(x-${n})(x+${n})=0$ なので $x=${n}$ または $x=-${n}$。`);
export const equationBanks=[
 J(chapter,"linear-equation","等式の変形と一次方程式","等しさを保つ操作で、文字の値を求めます。",[m`方程式の解は、代入すると等式が成り立つ文字の値です。両辺に同じ数を加減しても、同じ非零の数を掛けたり割ったりしても、等しさを保てます。`,"移項で符号が変わるのは、両辺から同じ項を引いているからです。理由が分からなくなったら両辺に行う操作を書きます。"],"求めた値は元の式へ戻して確かめます。",[S("linear","両辺を同じように変形する","定数の項を除いてから係数で割ります。",ns.map(n=>equation(n))),S("fraction","分数のある方程式","分数を含む項を残してから掛けます。",ns.map(n=>equation(n,true)))],sec[0]),
 J(chapter,"simultaneous","連立方程式","二つの条件を同時に満たす一組を求めます。",[m`一つの文字を消して、まず一つの方程式にします。加減法は二式を足し引きする方法、代入法は一方の式をもう一方へ入れる方法です。`,"一つの文字が求まったら、もう一つも求めます。一方の式だけでなく両方で検算します。"],"消しやすい文字と方法を選びます。",[S("eliminate","加減法","符号が反対の項を足して消します。",ns.map(n=>simultaneous(n))),S("substitute","代入法","既に表されている式を使います。",ns.map(n=>simultaneous(n,true)))],sec[0]),
 J(chapter,"square-roots","平方根と根号","平方根全体と、根号が表す一つの値を区別します。",[m`二乗して $a$ になる数が $a$ の平方根です。$a>0$ なら $\sqrt a,-\sqrt a$ の二つ。$a=0$ なら零だけで、$a<0$ に実数の平方根はありません。`,m`$\sqrt a$ は非負の方です。特に $\sqrt{x^2}=|x|$ であり、負の数をそのまま外へ出すことはできません。`],"何を求める問いかを先に読みます。",[S("radical","根号の値","非負の方を選びます。",ns.map(n=>roots(n))),S("both","平方根をすべて求める","正負二つを確かめます。",ns.map(n=>roots(n,true)))],sec[1]),
 J(chapter,"quadratic-equation","二次方程式と積が零になる条件","二乗の条件や因数分解から、解を落とさずに求めます。",[m`$AB=0$ なら $A=0$ または $B=0$。積が零でない場合にこの考え方を使うことはできません。`,m`$x^2=a$ では、実数解は $a>0$ なら正負二つ、$a=0$ なら零だけ、$a<0$ ならありません。一般の二次方程式も、両辺に同じ数を足して平方の形に直すと解けます。`,m`$ax^2+bx+c=0$（$a\ne0$）の両辺を $a$ で割り、$\left(\frac{b}{2a}\right)^2$ を補うと $\left(x+\frac{b}{2a}\right)^2=\frac{b^2-4ac}{4a^2}$。したがって $b^2-4ac\geqq0$ のとき $x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}$。右辺が負なら実数解はありません。`],"文字を含む因数で両辺を割る前に、零になる解を落とさないか考えます。",[S("square","二乗の方程式","非負の根だけで終えません。",ns.map(n=>quadratic(n))),S("zero-product","積を零にする","二つの因数を別々に零と置きます。",ns.map(n=>quadratic(n,true))),squareCondition,generalQuadratic],sec[1])
];
equationBanks.splice(2,0,equationExtraBanks[1]);
equationBanks.splice(4,0,equationExtraBanks[0]);
export const equationChapter=finish(chapter,"equations",equationBanks,sec);
