import {J,S,m,q,ns,finish} from "./junior-authoring";
const chapter="文字と式の基礎",sec=["文字の読み方と計算","展開と因数分解"];
const substitute=(n:number,square=false)=>q(m`$x=-${n}$ のとき、$${square?"x^2":"2x+3"}$ の値を求めなさい。`,m`$${square?n*n:3-2*n}$。`,"負の数を代入するときは括弧で囲みます。",square?m`$x^2=(-${n})^2=${n*n}$。`:m`$2(-${n})+3=${3-2*n}$。文字は数を表します。`);
const collect=(n:number,distribute=false)=>q(distribute?m`$3(x-${n})$ を展開しなさい。`:m`$${n}x+2x-3$ を簡単にしなさい。`,distribute?m`$3x-${3*n}$。`:m`$${n+2}x-3$。`,distribute?"括弧の中のすべての項に掛けます。":"文字の部分が同じ項だけをまとめます。",distribute?m`$3\cdot x-3\cdot${n}=3x-${3*n}$。`:m`$(${n}+2)x-3=${n+2}x-3$。定数の項は別に残します。`);
const monomial=(n:number,divide=false)=>q(divide?m`$${6*n}x^2y\div(3xy)$ を簡単にし、元の割り算の条件も答えなさい。`:m`$(${n}x)(-2x)$ を計算しなさい。`,divide?m`$${2*n}x$。ただし $x\ne0,y\ne0$。`:m`$-${2*n}x^2$。`,divide?"割る式が零でないことを確認して共通因数を約分します。":"数の部分と文字の部分をそれぞれ掛けます。",divide?m`$\frac{${6*n}xxy}{3xy}=${2*n}x$。約分しても元の $3xy\ne0$ という条件は残ります。`:m`$${n}\cdot(-2)\cdot x\cdot x=-${2*n}x^2$。`);
const expand=(n:number,square=false)=>q(square?m`$(x+${n})^2$ を展開しなさい。`:m`$(x+${n})(x-1)$ を展開しなさい。`,square?m`$x^2+${2*n}x+${n*n}$。`:m`$x^2${n===1?"":n===2?"+x":`+${n-1}x`}-${n}$。`,"一つ目の括弧の各項を、二つ目の各項に掛けます。",square?m`$(x+${n})(x+${n})=x^2+${n}x+${n}x+${n*n}$。二つの中間の項を忘れません。`:m`$x^2-x+${n}x-${n}$ の同類項をまとめます。`);
const factor=(n:number,product=false)=>q(product?m`$x^2+${n+2}x+${2*n}$ を因数分解しなさい。`:m`$${n}x+${3*n}$ を因数分解しなさい。`,product?m`$(x+${n})(x+2)$。`:m`$${n}(x+3)$。`,product?"和が一次の係数、積が定数項になる二数を探します。":"各項に共通して掛かっている因数を取り出します。",product?m`二数は $${n},2$。和 $${n+2}$、積 $${2*n}$。展開して元の式に戻ることを確かめます。`:m`$${n}x+${n}\cdot3=${n}(x+3)$。展開はこの逆の操作です。`);
export const algebraBanks=[
 J(chapter,"substitution","文字の意味と代入","文字の場所へ、指定された数を入れます。",[m`$2x$ は $2\times x$、$x^2$ は $x\times x$ の省略です。$2x$ と $x^2$ は別の式です。`,"式の値は文字に数を入れて求めます。文字式を整理することと、特定の値を求めることを分けて考えます。"],"負の数は括弧ごと代入します。",[S("linear","掛け算を読む","係数と文字の積です。",ns.map(n=>substitute(n))),S("square","累乗に代入する","同じ数を二回掛けます。",ns.map(n=>substitute(n,true)))],sec[0]),
 J(chapter,"like-terms","同類項と分配法則","まとめられる項と、括弧の外し方を確かめます。",[m`$3x+2x=(3+2)x=5x$。文字の部分が同じ項を同類項といいます。$x$ と $x^2$、文字の項と定数の項はまとめません。`,m`$a(b+c)=ab+ac$。括弧の前が負でも、中のすべての項に掛けます。`],"足し算でまとめるときと、掛け算を配るときの規則を区別します。",[S("collect","同類項をまとめる","係数を足します。",ns.map(n=>collect(n))),S("distribute","括弧を外す","一方だけでなく両方に掛けます。",ns.map(n=>collect(n,true)))],sec[0]),
 J(chapter,"monomials","文字式の掛け算と割り算","数と文字を分け、掛けた個数を数えます。",[m`$x^2x^3=x^5$ は、同じ文字を合わせて五回掛けた式です。$x+x$ のような加法とは違います。`,m`割り算は分数で書き、分子と分母の共通因数を約分します。分母が零になる値は除きます。`],"指数は掛けた個数です。係数まで指数にしないようにします。",[S("multiply","単項式の積","係数の積と文字の積を求めます。",ns.map(n=>monomial(n))),S("divide","共通因数を約分する","元の分母条件を残します。",ns.map(n=>monomial(n,true)))],sec[0]),
 J(chapter,"expansion","括弧の積と展開","すべての組の積を書き出してからまとめます。",[m`$(a+b)(c+d)=ac+ad+bc+bd$。一つずつ掛けて、抜けがないようにします。`,m`$(x+a)^2=x^2+2ax+a^2$。$(x+a)(x-a)=x^2-a^2$ は中間の項が打ち消し合う形です。`],"公式の形が見えないときも、分配法則に戻れます。",[S("product","二つの括弧の積","四つの積を順に書きます。",ns.map(n=>expand(n))),S("square","和の平方","中間の項も二つ生じます。",ns.map(n=>expand(n,true)))],sec[1]),
 J(chapter,"factorization","因数分解の基本","足し算で書かれた式を、掛け算の形へ戻します。",[m`因数分解は積の形へ直すことです。まず全項に共通する因数を探します。`,m`$x^2+(a+b)x+ab=(x+a)(x+b)$。候補を見付けたら、展開して三つの係数が元に戻るか確かめます。`],"式が零に等しいとは限りません。因数分解しただけで文字の値を決めないようにします。",[S("common","共通因数を出す","どの項にも含まれる因数です。",ns.map(n=>factor(n+1))),S("product","和と積から分ける","展開して検算します。",ns.map(n=>factor(n,true)))],sec[1])
];
export const algebraChapter=finish(chapter,"algebra",algebraBanks,sec);
