export type Point=[number,number];
export type Plot={caption:string;axis?:[string,string];limit:number;points:{at:Point;label:string;offset?:Point}[];paths:{points:Point[];arrow?:boolean;dashed?:boolean}[]};
const m=String.raw;
const sample=(f:(t:number)=>Point,a:number,b:number,n=100)=>Array.from({length:n+1},(_,i)=>f(a+(b-a)*i/n));
export const mathCPlots:Record<string,Plot>={
 "mc-vector-components":{limit:5,caption:m`例題の $A(3,-1)$ から $B(2,3)$ へ。横に $-1$、縦に $4$ 動くので $\overrightarrow{AB}=(-1,4)$。`,points:[{at:[3,-1],label:"$A$"},{at:[2,3],label:"$B$"}],paths:[{points:[[3,-1],[2,3]],arrow:true},{points:[[3,-1],[2,-1],[2,3]],dashed:true}]},
 "mc-vector-sum":{limit:5,caption:m`例題の $\vec a=(3,-2),\vec b=(-1,3)$。二本目の始点を一本目の終点へ移すと、全体は $(2,1)$ です。`,points:[{at:[3,-2],label:"$A$"},{at:[2,1],label:"$P$"}],paths:[{points:[[0,0],[3,-2]],arrow:true},{points:[[3,-2],[2,1]],arrow:true},{points:[[0,0],[2,1]],arrow:true,dashed:true}]},
 "mc-vector-scalar":{limit:7,caption:m`例題の $\vec a=(3,-1)$ と $-2\vec a=(-6,2)$。同一直線上で逆向き、長さは二倍です。`,points:[{at:[3,-1],label:m`$\vec a$`},{at:[-6,2],label:m`$-2\vec a$`}],paths:[{points:[[0,0],[3,-1]],arrow:true},{points:[[0,0],[-6,2]],arrow:true}]},
 "mc-vector-intersection":{limit:7,caption:m`例題の二直線は $(3,3)$ で交わります。二つの表示の成分が一致する点です。`,points:[{at:[3,3],label:"$P(3,3)$",offset:[0,-32]}],paths:[{points:[[-1,-1],[6,6]]},{points:[[-1,7],[7,-1]]}]},
 "mc-complex-point":{axis:[m`$\mathrm{Re}$`,m`$\mathrm{Im}$`],limit:5,caption:m`例題の $z=-3+2i$ は点 $(-3,2)$。点線の横と縦から、原点までの距離を求めます。`,points:[{at:[-3,2],label:"$z$"}],paths:[{points:[[0,0],[-3,2]]},{points:[[-3,0],[-3,2],[0,2]],dashed:true}]},
 "mc-complex-rotation":{axis:[m`$\mathrm{Re}$`,m`$\mathrm{Im}$`],limit:6,caption:m`例題の中心 $\alpha=1+2i$ から見て、$z=4+3i$ を反時計回りに直角だけ回すと $w=5i$。中心からの距離は同じです。`,points:[{at:[1,2],label:m`$\alpha$`,offset:[8,4]},{at:[4,3],label:"$z$"},{at:[0,5],label:"$w$"}],paths:[{points:[[1,2],[4,3]],arrow:true},{points:[[1,2],[0,5]],arrow:true},{points:sample(t=>[1+Math.sqrt(10)*Math.cos(t),2+Math.sqrt(10)*Math.sin(t)],Math.atan2(1,3),Math.atan2(1,3)+Math.PI/2),dashed:true}]},
 "mc-complex-roots":{axis:[m`$\mathrm{Re}$`,m`$\mathrm{Im}$`],limit:4,caption:m`例題の $z^3=27$ の三つの解。半径 $3$ の円を三等分し、どの解も三乗すると正の実軸上へ戻ります。`,points:[0,1,2].map(k=>({at:[3*Math.cos(k*2*Math.PI/3),3*Math.sin(k*2*Math.PI/3)] as Point,label:`$z_${k+1}$`})),paths:[{points:sample(t=>[3*Math.cos(t),3*Math.sin(t)],0,2*Math.PI),dashed:true}]},
 "mc-parabola":{limit:6,caption:m`例題の $y^2=12x$。焦点は $(3,0)$、準線は $x=-3$。曲線上の $P(3,6)$ は、どちらからも距離 $6$ です。`,points:[{at:[3,0],label:"$F$"},{at:[3,6],label:"$P$",offset:[18,0]}],paths:[{points:sample(y=>[y*y/12,y],-6,6)},{points:[[-3,-6],[-3,6]],dashed:true},{points:[[3,0],[3,6],[-3,6]],dashed:true}]},
 "mc-ellipse":{limit:6,caption:m`例題の $\frac{x^2}{25}+\frac{y^2}9=1$。長半径は $5$、短半径は $3$、焦点は $(\pm4,0)$。`,points:[{at:[4,0],label:"$F_2$"},{at:[-4,0],label:"$F_1$"},{at:[0,3],label:"$(0,3)$",offset:[30,-23]}],paths:[{points:sample(t=>[5*Math.cos(t),3*Math.sin(t)],0,2*Math.PI)}]},
 "mc-hyperbola":{limit:6,caption:m`例題の $\frac{x^2}9-\frac{y^2}{16}=1$。頂点は $(\pm3,0)$、焦点は $(\pm5,0)$、点線は漸近線です。`,points:[{at:[5,0],label:"$F_2$"},{at:[-5,0],label:"$F_1$"}],paths:[{points:sample(t=>[3*Math.cosh(t),4*Math.sinh(t)],-1.1,1.1)},{points:sample(t=>[-3*Math.cosh(t),4*Math.sinh(t)],-1.1,1.1)},{points:[[-4.5,-6],[4.5,6]],dashed:true},{points:[[-4.5,6],[4.5,-6]],dashed:true}]},
 "mc-parametric-elimination":{limit:6,caption:m`範囲付きの例題：$x=t^2,y=t+3$、$t\geqq0$。実線が軌跡、点線は同じ方程式でも範囲外の部分です。`,points:[{at:[0,3],label:"$(0,3)$",offset:[-32,-22]}],paths:[{points:sample(t=>[t*t,t+3],0,Math.sqrt(5.5))},{points:sample(t=>[t*t,t+3],-Math.sqrt(5.5),0),dashed:true}]},
 "mc-parametric-ellipse":{limit:4,caption:m`例題の $x=3\cos t,y=2\sin t$。$t=0$ から $t=\frac\pi2$ へ、右端から上へ進みます。`,points:[{at:[3,0],label:"$t=0$",offset:[0,10]},{at:[0,2],label:m`$t=\frac\pi2$`,offset:[0,-36]}],paths:[{points:sample(t=>[3*Math.cos(t),2*Math.sin(t)],0,2*Math.PI)},{points:sample(t=>[3*Math.cos(t),2*Math.sin(t)],.1,.7),arrow:true}]},
 "mc-polar-equation":{limit:7,caption:m`円の例題：$r=6\cos\theta$ は中心 $(3,0)$、半径 $3$ の円。原点も曲線に含まれます。`,points:[{at:[3,0],label:"$C$"}],paths:[{points:sample(t=>[3+3*Math.cos(t),3*Math.sin(t)],0,2*Math.PI)}]}
};
