import type {PrerequisitePlan} from "./prerequisite-plans";
const r=(lesson:string,families:string,checks:string,reason:string):PrerequisitePlan=>({lesson,families:families.split(" "),checks:checks?checks.split(" "):[],reason});
export const calculusPrerequisites:PrerequisitePlan[]=[
 r("cubic-expansion","core","expand-product square-expand","三乗を二乗と一乗の積として展開する。"),
 r("cubic-factorization","core","factor-common expand-product","積の形へ戻し、展開で確かめる。"),
 r("binomial-meaning","core","product-count combination","各因数から項を選ぶことと組合せを結び付ける。"),
 r("binomial-coefficient","core","combination power","必要な次数になる選択を数える。"),
 r("polynomial-division","core","expand collect","商を掛け戻し、同じ次数の項を引く。"),
 r("rational","cancel","factor cancel-factor","共通因数の積を作って約分する。"),
 r("rational","domain","denominator","約分前の分母で使えない値を調べる。"),
 r("rational","structure","cancel-factor","項の一部ではなく因数全体を約分する。"),
 r("rational-product","core","cancel-factor fraction-divide","割る式の非零条件を残して逆数を掛ける。"),
 r("rational-sum","core","fraction-expression","分母をそろえ、分子全体を加減する。"),
 r("identities","core","expand-product","すべての入力で等しくなる係数を比較する。"),
 r("equalities","core","expand-product fraction-expression","同じ式への変形を示す。"),
 r("inequalities","core","square-expand","両辺の差を二乗などの非負の形へ直す。"),
 r("amgm","core","","非負条件と等号条件を問題の式に即して確認する。"),
 r("complex-numbers","core","root","実数の平方根と虚数単位を区別する。"),
 r("complex-arithmetic","core","expand-product","展開後に虚数単位の二乗を置き換える。"),
 r("quadratic-equations","core","quadratic-solve","係数の符号を解の公式に入れる。"),
 r("discriminant","core","discriminant","根号の中の符号と解の個数を結び付ける。"),
 r("root-relations","core","","係数と解の和・積の対応を専用補足で確認する。二乗和の変形は個別に指定する。"),
 r("equation-from-roots","core","zero expand-product","解を零にする因数から式を作る。"),
 r("remainder-theorem","core","input-expression","割る一次式が零になる値を恒等式に入れる。"),
 r("factor-theorem","core","zero substitution","余りが零なら因数になることを使う。"),
 r("higher-equations","core","factor zero","因数に分けて各方程式の全解を集める。"),
 r("points","membership coordinate substitution","point substitution","座標を式に代入し、縦の値が一致するか調べる。"),
 r("points","reverse","zero root","指定された縦の値をもつ横の値をすべて求める。"),
 r("coordinate-conditions","coordinate-conditions","coordinates","軸や直線上にある条件を座標で表す。"),
 r("point-distance","point-distance","distance difference","横と縦の差を直角二辺にする。"),
 r("section-points","internal-section external-section","ratio coordinates","比の向きと座標の対応を分ける。"),
 r("line-equations","line-through-points","slope point","傾きを計算し、通る点を代入する。"),
 r("line-equations","axis-parallel-line","coordinates","横または縦の座標が一定になる。"),
 r("parallel-perpendicular","parallel-line perpendicular-line","slope","二直線の傾きの関係を使う。"),
 r("point-line-distance","point-line-distance","substitution absolute","点の座標を入れて絶対値を取る。"),
 r("circle-equation","circle-center-radius circle-from-diameter circle-through-three-points","distance point","中心からの距離と通る点の条件を使う。"),
 r("circle-completing-square","circle-completing-square","square","二つの変数を別々に平方完成する。"),
 r("figure-intersections","line-intersection circle-line-intersection","point equation","同じ点が二つの式を満たす。"),
 r("circle-line-position","circle-line-position","discriminant distance","共有点の個数または中心からの距離で判断する。"),
 r("circle-tangents","tangent-at-point tangents-from-point","point slope","接点と直角の条件を別々に使う。"),
 r("two-circle-position","two-circle-position","distance absolute","中心間距離と半径の和・差を比べる。"),
 r("circle-common-chord","circle-common-chord","point expand","共通点が両式を満たすことから差を取る。"),
 r("locus-equations","equidistance-locus midpoint-range-locus distance-ratio-locus","point distance","点が満たす距離条件を式へ直し、逆も確かめる。"),
 r("inequality-regions","half-plane-region intersection-region","point inequality-end","境界上の点と、どちら側の点かを区別する。"),
 r("trig-radians","conversion sector","ratio","一周との割合から角・弧長・面積を求める。"),
 r("trig-unit-circle","coordinate special","trig coordinates","三角比を単位円の座標として読む。"),
 r("trig-angle-change","reflection complement","trig-coordinate","対称移動した点の座標を読む。"),
 r("trig-identities","recover identity","trig-coordinate root","二乗の関係と角による符号を分ける。"),
 r("trig-graphs","wave tangent-graph","trig-coordinate radians","一周に対応する周期と使えない角を読む。"),
 r("trig-equations","basic-equation transformed-equation","trig-coordinate radians","同じ座標になる角を範囲内ですべて求める。"),
 r("trig-inequalities","sine-cosine-region tangent-region","trig-coordinate inequality-end","条件を満たす弧や区間を残す。"),
 r("trig-addition","sin-cos-addition tan-addition","trig-coordinate fraction","角の和の公式へ代入する。"),
 r("trig-double-half","double-angle half-angle","trig-identity root","二倍角の式から二乗を表し、符号を決める。"),
 r("trig-synthesis","synthesis-expression synthesis-range synthesis-equation","trig-coordinate distance","係数を半径と角に対応させる。"),
 r("exponent-extension","zero-negative-power root-rational-power","power root","累乗と根号の意味を保って指数を広げる。"),
 r("exponent-laws","power-operations base-rewrite","exponent","底をそろえ、指数の計算をする。"),
 r("exponential-graph","exp-points-monotonicity exp-range-shift","exponent point","累乗の値と入力の変化を結び付ける。"),
 r("exponential-equations","exp-equation exp-substitution","exponent equation","同じ底または一つの文字の式に直す。"),
 r("exponential-equations","exp-increasing-inequality exp-decreasing-inequality","exponent inequality-end","底に応じた増減を確かめて指数を比べる。"),
 r("logarithm-meaning","log-value","power","何乗すると真数になるかを考える。"),
 r("logarithm-meaning","log-definition-conditions","inequality-end","底と真数に付く条件を区別する。"),
 r("logarithm-laws","log-product-quotient log-power-expand","log-value","対数を指数の関係に戻す。"),
 r("logarithm-base-change","base-change-value base-change-product","log-value fraction-divide","同じ底の対数で比を作る。"),
 r("logarithmic-graph","log-points-monotonicity log-range-shift","log-value point","真数の条件とグラフ上の点を読む。"),
 r("logarithmic-equations","log-equation log-sum-equation log-substitution","log log-product","先に真数条件を残し、対数の法則でまとめる。"),
 r("logarithmic-equations","log-increasing-inequality log-decreasing-inequality","log inequality-linear","真数条件と底による不等号の向きを区別する。"),
 r("common-logarithm","common-log-evaluation integer-digits fractional-digits growth-count","log-value inequality-end","十の累乗と数量の範囲を対応させる。"),
 r("average-rate","average-rate","slope substitution","関数値を出し、出力の差を入力の差で割る。"),
 r("derivative-at-point","derivative-at-point","difference-quotient square-expand","平均変化率を整理してから間隔を零に近づける。"),
 r("derivative-function","derivative-function","input-expression square-expand","式の入力を丸ごと置き換えて差商を作る。"),
 r("polynomial-differentiation","polynomial-rules","","累乗と定数の微分をこの問題の式で確かめる。"),
 r("tangent-line","tangent-line","derivative slope","接点の座標と傾きを別々に計算する。"),
 r("derivative-sign","monotonicity","zero inequality-linear","導関数が零になる点と区間ごとの符号を調べる。"),
 r("local-extrema","local-extrema","derivative-sign","零になるだけでなく、前後で増減が変わるか調べる。"),
 r("graph-sketch","graph-sketch","derivative-sign point","増減とグラフ上の点をまとめる。"),
 r("closed-interval-extrema","closed-interval-extrema","derivative-sign substitution","停留点と定義域の端の値を比べる。"),
 r("derivative-applications","equation-root-count inequality-monotonicity inequality-proof","derivative-sign","差の増減や極値から根や符号を判断する。"),
 r("antiderivatives","recognize-antiderivative indefinite","power-derivative","微分して元に戻る関数を探す。"),
 r("polynomial-integrals","indefinite","integral","既に和の形になった式を項ごとに積分する。"),
 r("polynomial-integrals","expand-integrate","integral expand-product","積を展開して項ごとに積分できる形へ直す。"),
 r("integral-constant","initial-value","substitution equation","与えられた点を原始関数に入れて定数を決める。"),
 r("definite-integrals","evaluate-definite","integral substitution","原始関数の上端の値から下端の値を引く。"),
 r("definite-properties","reverse-bounds split-interval linear-integral","","与えられた積分値に向き・区間の分割・線形性を使う。原始関数は求めない。"),
 r("area-with-axis","axis-one-sign axis-split","zero endpoint-value","横軸との交点と上下を調べ、正の面積を足す。"),
 r("area-between-curves","between-enclosed between-bounded between-split","intersection endpoint-value","交点で区間を決め、上から下を引く。"),
 // Math III. Preparation-only tasks are overridden per question below, not by broad lesson rules.
 r("m3-function-input","value","substitution power","入力を括弧で囲み代入する。"),
 r("m3-function-input","expression","substitution square-expand","式全体を入力として置き換える。"),
 r("m3-domain-range","domain","denominator root","分母と根号の条件から入力の範囲を決める。"),
 r("m3-domain-range","range","point inequality-end","可能な入力から実現する出力を調べる。"),
 r("m3-rational-functions","shape condition","denominator point","定義されない入力とグラフの位置を分ける。"),
 r("m3-radical-functions","shape condition","root inequality-linear","根号内が非負の範囲を残す。"),
 r("m3-composition","order structure","input-expression","内側の出力を外側の入力に入れる。"),
 r("m3-composition-domain","condition retained","","分母・根号・真数のどれが現れるかは設問ごとに指定する。"),
 r("m3-inverse-functions","linear branch","point equation","入出力を入れ替えても一つの値になる範囲を選ぶ。"),
 r("m3-graph-equations","root fraction","intersection denominator","グラフ上の等式と使えない値を保つ。"),
 r("m3-sequence-basics","term","substitution","項番号を一般項へ入れる。"),
 r("m3-sequence-basics","sum","sigma sum-to-term","和を読むことと、一項を取り出すことを分ける。"),
 r("m3-sequence-rational-limit","finite growth","cancel-factor reciprocal-limit","最も高い次数で割り、残る項の極限を取る。"),
 r("m3-sequence-radical-limit","difference","conjugate root-normalize reciprocal-limit","有理化・根号の整理・極限を別々に確かめる。"),
 r("m3-sequence-radical-limit","scale","root-normalize reciprocal-limit","正の項番号で根号から二乗を取り出す。"),
 r("m3-sequence-radical-limit","reciprocal-limit","conjugate root-normalize reciprocal-limit","分母の差を有理化し、次数をそろえて極限を取る。"),
 r("m3-geometric-sequence-limit","shrink other","","公比の大きさと符号、初項が零の場合を専用補足で確認する。"),
 r("m3-sequence-squeeze","zero shift","absolute reciprocal-limit","値の大きさを零へ近づく式で抑える。"),
 r("m3-infinite-series-meaning","partial","","与えられた部分和の極限を調べる。実際に和を作る設問は個別に指定する。"),
 r("m3-infinite-series-meaning","necessary","","一般項の収束と部分和の収束の違いを直接確かめる。"),
 r("m3-geometric-series","sum","geometric-sum partial-sum-limit","有限の部分和を作ってから収束を調べる。"),
 r("m3-geometric-series","condition","","初項が零の場合も含め、収束条件を問題の式で調べる。"),
 r("m3-telescoping-series","split","partial","係数を合わせて差に分ける。"),
 r("m3-telescoping-series","ends","telescoping partial-sum-limit","有限和の端を残した後で極限を取る。"),
 r("m3-recurrence-limit","formula verify","geometric-term reciprocal-limit","漸化式から一般項を確かめて極限を調べる。"),
 r("m3-limit-and-value","near point","point substitution","その点での値と近くの値を分ける。"),
 r("m3-one-sided-limits","absolute","absolute inequality-end","近づく側で絶対値の符号を外す。"),
 r("m3-one-sided-limits","sides","","左右の値を別々に調べて比較する。"),
 r("m3-direct-substitution","evaluate","substitution","代入できる式で値を計算する。"),
 r("m3-direct-substitution","condition","","代入の可否と片側の定義域を式ごとに確かめる。"),
 r("m3-factorization-limits","factor","factor cancel-factor","近くで零でない因数を約分して極限を取る。"),
 r("m3-factorization-limits","compare","","関数値と極限の等しさは連続性を含めて直接調べる。"),
 r("m3-rationalizing-limits","root","conjugate cancel-factor","共役を掛け、零へ近づく因子を取り出す。"),
 r("m3-rationalizing-limits","fraction","fraction-expression cancel-factor","通分して差を一つの分子へまとめる。"),
 r("m3-limits-at-infinity","ratio","cancel-factor reciprocal-limit","主要な次数で割って残る項を見る。"),
 r("m3-limits-at-infinity","root","root-square root-normalize","根号から出す文字の符号を保つ。"),
 r("m3-trigonometric-limits","match transform","radians trig-identity","角と分母を同じ小さい量へそろえる。"),
 r("m3-e-and-natural-log","constant log","log-value","指数と対数を逆の関係として読む。"),
 r("m3-exponential-log-limits","end basic","log-value exponent","指数・対数の基本極限へ式を合わせる。"),
 r("m3-continuity","fill check","point","極限値と定義された関数値を照合する。"),
 r("m3-intermediate-value","exist scope","","連続性と端点の符号を、この定理の条件として確かめる。"),
 r("m3-derivative-meaning","m3-derivative-meaning-average","difference-quotient","二点間の変化量の比を取る。"),
 r("m3-derivative-meaning","m3-derivative-meaning-value-slope","power-derivative substitution","関数値と微分係数を別々に計算する。"),
 r("m3-derivative-definition","derivative-definition","input-expression square-expand cancel-factor","差商を作り、共通因数を約分してから極限を取る。"),
 r("m3-derivative-definition","m3-derivative-definition-reciprocal","fraction-expression cancel-factor","分数の差を通分してから間隔で割る。"),
 r("m3-derivative-definition","m3-derivative-definition-radical","conjugate cancel-factor","根号の差商を有理化する。"),
 r("m3-differentiability","differentiability m3-differentiability-endpoint","difference-quotient","左右または定義域内の差商が有限の同じ値へ近づくか調べる。"),
 r("m3-power-derivatives","power-derivatives","power-derivative exponent","根号・逆数を累乗で表す。"),
 r("m3-trigonometric-derivatives","trigonometric-derivatives","radians trig-coordinate","角の単位と三角関数の符号を確かめる。"),
 r("m3-exponential-log-derivatives","exponential-log-derivatives","log-value exponent","関数の種類と定義域を区別する。"),
 r("m3-product-derivative","product-derivative","power-derivative","積の各因子を別々に微分する。"),
 r("m3-quotient-derivative","quotient-derivative","power-derivative denominator","分子・分母を別々に微分し元の分母条件を残す。"),
 r("m3-chain-rule","chain-rule","power-derivative input-expression","外側の微分へ内側の微分を掛ける。"),
 r("m3-chain-rule-functions","chain-rule-functions","chain","内側の関数の微分を忘れない。"),
 r("m3-simplify-before-derivative","simplify-before-derivative","cancel-factor expand-product","式を簡単にしてから微分する。"),
 r("m3-logarithmic-differentiation","logarithmic-differentiation","log-product chain","対数の法則と合成関数の微分を使う。"),
 r("m3-implicit-derivative","implicit-derivative","chain product-derivative","未知の関数も入力に応じて変わるとして微分する。"),
 r("m3-inverse-derivative","inverse-derivative","chain point","対応する入力を確かめ、合成した恒等式を微分する。"),
 r("m3-parametric-derivative","parametric-derivative","slope power-derivative","媒介変数による縦と横の変化量の比を取る。"),
 r("m3-second-derivative","second-derivative","","一度微分した式をもう一度微分する。関数の種類に応じた操作は個別に指定する。"),
 r("m3-choose-derivative","choose-derivative","product-derivative chain","積と合成を式の外側から区別する。"),
 r("m3-tangent-at-point","tangent point-slope","derivative slope","接点と接線の傾きを別に求める。"),
 r("m3-normal-line","normal","derivative slope","接線の傾きから垂直な方向を求める。"),
 r("m3-normal-line","vertical-normal","","接線が水平のとき、法線は縦線になることを直接確かめる。"),
 r("m3-unknown-contact","through-point parallel","derivative point","未知の接点で接線を表し、通過点などの条件を入れる。"),
 r("m3-linear-approximation","approx approx-limit","derivative slope","基準の点と傾きで近くの値を表す。"),
 r("m3-mean-value-theorem","mvt-point","difference-quotient derivative","二点の平均変化率と一致する微分係数を探す。"),
 r("m3-monotonicity-extrema","sign-extrema stationary","derivative-sign zero","停留点の前後で導関数の符号が変わるか調べる。"),
 r("m3-global-extrema","closed-max","derivative-sign substitution","端点と内部の候補の値を比べる。"),
 r("m3-global-extrema","open-max","inequality-end","境界の値が定義域内で実現するか確かめる。"),
 r("m3-concavity-inflection","concavity inflection-test","derivative-sign","二階微分の符号と、その前後の変化を調べる。"),
 r("m3-curve-sketch","smooth-sketch split-sketch","derivative-sign denominator","定義域を分け、極限と増減をそろえる。"),
 r("m3-roots-existence-count","one-root two-roots","derivative-sign point","増減による高々何個と、存在を分けて示す。"),
 r("m3-derivative-inequalities","difference-proof","derivative-sign","両辺の差の最小値を調べる。"),
 r("m3-velocity-acceleration","kinematic-values motion-direction","derivative","位置を微分して速度、さらに微分して加速度を求める。"),
 r("m3-velocity-acceleration","speed-change","absolute derivative-sign","速度の絶対値の増減を見る。"),
 r("m3-optimization-model","rectangle fence constrained-area","derivative-sign inequality-end","数量から定義域を決め、端も含めて比較する。"),
 r("m3-optimization-model","area-infimum","inequality-end","下限と実現する最小値を区別する。"),
 r("m3-antiderivative-constant","constant","power-derivative","候補を微分して元の関数へ戻るか確かめる。"),
 r("m3-antiderivative-constant","initial-value","integral substitution","原始関数に条件を代入して定数を決める。"),
 r("m3-power-integrals","power reciprocal","integral exponent","累乗の形と指数が負一の場合を分ける。"),
 r("m3-trig-basic-integrals","sin-cos tan-primitive","integral trig-identity","微分で元に戻る三角関数を考える。"),
 r("m3-exponential-integrals","exponential","integral exponent","元の関数に戻る係数を確認する。"),
 r("m3-linear-inner-integrals","linear-inner","chain integral","内側を微分した係数を補う。"),
 r("m3-reverse-chain-integrals","reverse-chain","chain","内側の微分が外に掛かっているかを照合する。"),
 r("m3-log-derivative-integrals","log-form","chain denominator","分母の微分が分子にあるかと、分母の非零条件を確認する。"),
 r("m3-algebra-before-integrals","expand","expand-product integral","積分できる項の和へ展開する。"),
 r("m3-algebra-before-integrals","divide","cancel-factor integral","項ごとの商へ直し、元の定義域を保つ。"),
 r("m3-partial-fractions","partial-fractions","partial integral","差への分解を確認した後、それぞれを積分する。"),
 r("m3-trig-transform-integrals","half-angle","trig-double integral","二乗を二倍角の一次式へ直す。"),
 r("m3-trig-transform-integrals","product-sum","trig-identity integral","積を和へ変形して積分する。"),
 r("m3-substitution-integrals","substitution","chain integral","微分の関係を使い、積分変数を統一する。"),
 r("m3-radical-substitution","radical-sub","root-square chain","根号の値を新しい変数にし、その非負条件を残す。"),
 r("m3-trig-substitution","trig-sub","trig-identity chain","根号内を三角関数の二乗へ直す。"),
 r("m3-trig-substitution","angle-sign","root-square trig-coordinate","根号から取り出す三角関数の符号を角の範囲で決める。"),
 r("m3-parts-introduction","parts-exp","product-derivative integral","積の微分を逆に使う。"),
 r("m3-parts-log-trig","parts-trig parts-log","product-derivative integral","微分する因子と積分する因子を選ぶ。"),
 r("m3-choose-integral","linear-inner reverse-chain","chain integral","内側の微分の有無を照合する。"),
 r("m3-choose-integral","expand","expand-product integral","積を和に直して各項を積分する。"),
 r("m3-choose-integral","parts-exp","product-derivative integral","積の微分の逆を使う。"),
 r("m3-definite-meaning","meaning value","endpoint-value","関数の集まりと両端の差の値を分ける。"),
 r("m3-endpoint-evaluation","endpoints","endpoint-value","下端を代入した式全体を引く。"),
 r("m3-endpoint-evaluation","domain","denominator","区間内で原始関数の関係を使えるか確認する。"),
 r("m3-integral-properties","linearity orientation split","","既知の積分値へ性質を使う。原始関数から計算する設問は個別に指定する。"),
 r("m3-dummy-variable","dummy parameter","","積分変数の改名と定数の扱いを専用補足で確認する。数値代入とは区別する。"),
 r("m3-definite-substitution","sub-value sub-bounds","substitution chain","新しい変数で両端と微分の関係をそろえる。"),
 r("m3-definite-parts","parts boundary","product-derivative endpoint-value","境界の積の値を忘れずに差を取る。"),
 r("m3-integral-symmetry","sym-value","input-expression","符号を反転した入力で偶奇性を調べ、対称区間で積分する。"),
 r("m3-integral-symmetry","sym-condition","","対称区間・区間全体での定義・関数の偶奇性を専用補足で確認する。"),
 r("m3-integral-function","ftc-compute","derivative","上端の変化に対応する関数値を考える。"),
 r("m3-moving-endpoints","upper-chain two-ends","chain endpoint-value","上下端の合成微分を符号付きで足す。"),
 r("m3-riemann-sums","sum-setup sum-limit","sigma rectangle-area","長方形の幅と高さを掛けて足す。"),
 r("m3-integral-bounds","bounds compare","","区間全体の関数の大小を積分の大小へ移す理由を専用補足で確認する。"),
 r("m3-integral-bounds","reverse-compare","inequality-linear","積分の向きを逆にすると負号が付き、大小関係も逆になる。"),
 r("m3-signed-area","area-setup","point absolute","グラフが軸の上か下かを確かめる。"),
 r("m3-signed-area","area-value","endpoint-value absolute","符号付きの積分値と正の面積を区別する。"),
 r("m3-between-curves","between-setup","intersection","共有点と上下の関係から区間と差を決める。"),
 r("m3-between-curves","between-value","intersection endpoint-value","交点で区切り、上から下を引いて積分する。"),
 r("m3-area-splitting","split-setup","intersection","上下が変わる交点で区間を分ける。"),
 r("m3-area-splitting","split-value","intersection endpoint-value","各区間で正の差を積分して足す。"),
 r("m3-horizontal-area","horizontal-setup horizontal-value","point equation","横の長さを縦の座標の式で表す。"),
 r("m3-cross-section-volume","section-setup section-value","rectangle-area","切り口の面積を位置の関数にする。"),
 r("m3-disk-volume","disk-setup disk-value","distance-sign power","回転軸からの距離を半径にして二乗する。"),
 r("m3-washer-volume","washer-setup washer-value","power difference","外側と内側の円の面積を引く。"),
 r("m3-washer-volume","shifted-setup shifted-value","distance-sign power","ずれた軸から測った二つの半径を使う。"),
 r("m3-rotation-direction","rotation-setup rotation-value","point equation","回転軸に垂直な断面の半径を対応する変数で表す。"),
 r("m3-rotation-direction","vertical-washer-setup vertical-washer-value","point distance-sign","縦の軸からの横の距離を内外の半径とする。"),
 r("m3-graph-length","length-setup length-value","distance derivative","小線分の長さを三平方で表す。"),
 r("m3-parametric-length","param-speed param-length","distance derivative","二方向の変化を合わせた速さを使う。"),
 r("m3-parametric-area","param-area-direction","","微分の関係と進行方向から面積の積分を組み立てる。計算は要求しない。"),
 r("m3-parametric-area","param-area-value","endpoint-value","媒介変数に直した面積の積分を計算する。"),
 r("m3-displacement-distance","displacement","endpoint-value","符号付き速度を積分する。"),
 r("m3-displacement-distance","distance","absolute endpoint-value","速度の符号で区間を分けて長さを足す。"),
 r("chapter-one-check","factor","expand-product","三次式の因数分解を展開で確かめる。"),
 r("chapter-one-check","sum","fraction-expression","異なる分母をそろえて加える。"),
 r("chapter-one-check","proof","square-expand","差を二乗で表し、等号条件まで示す。"),
 r("chapter-one-check","binomial","combination","必要な次数になる項の選び方を数える。"),
 r("chapter-one-check","identity","expand equation","両辺の係数を比較する。"),
 r("chapter-one-check","expansion","cubic-expand","三乗の展開で中間の項を落とさない。"),
 r("chapter-one-check","division","expand collect","商を掛け戻して引く。"),
 r("chapter-one-check","equality","square-expand","両方の平方を展開して差を取る。"),
 r("chapter-one-check","amgm","","正の条件と等号が成り立つ値を問題の式で確かめる。"),
 r("m3-functions-check","input composition","input-expression","式全体を入力へ代入する。"),
 r("m3-functions-check","domain","vertex inequality-end","頂点と端点の値から、実現する出力の範囲を求める。"),
 r("m3-functions-check","rational","denominator cancel-factor","分数関数を定数と真分数へ直す。"),
 r("m3-functions-check","radical","root-domain point","根号が零になる端と増減方向を読む。"),
 r("m3-functions-check","composite-domain","root-domain denominator","根号が分母にあるので、零を除いた正の条件を使う。"),
 r("m3-functions-check","inverse","equation point","入出力を入れ替えて元の値域を定義域にする。"),
 r("m3-functions-check","equation","root-domain zero","二乗する前の非負条件を残し、解を元の式で確かめる。"),
 r("m3-sequences-check","term","sigma sum-to-term","一項と部分和を区別する。"),
 r("m3-sequences-check","rational","cancel-factor reciprocal-limit","最も高い次数で割る。"),
 r("m3-sequences-check","radical","conjugate root-normalize reciprocal-limit","根号の差を有理化してから極限を取る。"),
 r("m3-sequences-check","geometric","","与えられた一般項の公比部分の極限を専用補足で確認する。"),
 r("m3-sequences-check","squeeze","absolute reciprocal-limit","差の絶対値を零へ近づく量で抑える。"),
 r("m3-sequences-check","series","geometric-sum partial-sum-limit","有限和を先に求め、その極限を取る。"),
 r("m3-sequences-check","recurrence","geometric-term equation","一定の値を引く漸化式から一般項を求める。"),
 r("m3-function-limits-check","direct","substitution","直接代入できる式を計算する。"),
 r("m3-function-limits-check","factor","factor cancel-factor","因数に分け、零でない範囲で約分する。"),
 r("m3-function-limits-check","trig","radians","基本極限の角と分母をそろえる。"),
 r("m3-function-limits-check","exp","","指数または対数の基本極限に合わせる部分を直接説明する。"),
 r("m3-function-limits-check","continuous","point substitution","極限と、その点で定義する値を一致させる。"),
 r("m3-function-limits-check","intermediate","","連続性と両端の符号を確認し、少なくとも一つの解の存在を示す。"),
];

// Per-item exceptions are necessary when a historical family combines different operations.
// These IDs, including their chapter copies, are tested; do not replace them with prose matching.
export const exercisePrerequisites:Record<string,string[]>={
 "root-relations-6-v1":["square-expand"],
 "root-relations-7-v1":["square-expand"],
 "root-relations-10-v1":["square-expand"],
 "m3-infinite-series-meaning-3-v1":["reciprocal-limit"],
 "m3-infinite-series-meaning-7-v1":["sigma"],
 "m3-infinite-series-meaning-11-v1":["reciprocal-limit"],
 "m3-geometric-sequence-limit-6-v1":["geometric-term"],
 "m3-geometric-sequence-limit-9-v1":["exponent"],
 "m3-second-derivative-guided-1-v1":["power-derivative"],
 "m3-second-derivative-guided-2-v1":["product-derivative"],
 "m3-second-derivative-practice-3-v1":["exponent","power-derivative"],
 "m3-second-derivative-practice-4-v1":["exponent","power-derivative"],
 "m3-second-derivative-practice-5-v1":["chain"],
 "m3-second-derivative-practice-6-v1":["power-derivative","substitution"],
 "m3-second-derivative-review-2-v1":["chain"],
 "m3-integral-properties-practice-3-v1":["endpoint-value"],
 "m3-integral-properties-practice-4-v1":["endpoint-value"],
 "m3-integral-properties-review-2-v1":["endpoint-value"],
 "r-practice-1-v1":["cancel-factor"],
 "r-guide-factor-v1":["factor"],
 "p-ready-order-v1":[],
 "m3-sequence-radical-limit-1-v1":["conjugate-product"],
 "m3-rationalizing-limits-1-v1":["conjugate-product"],
 "m3-geometric-series-8-v1":[],
 "m3-sequence-basics-6-v1":["sigma"],
 "m3-sequence-basics-10-v1":["sigma"],
 "m3-sequence-basics-4-v1":["sum-to-term"],
 "m3-sequence-basics-8-v1":["sum-to-term"],
 "m3-sequence-basics-12-v1":["sum-to-term"],
 "m3-telescoping-series-2-v1":["telescoping"],
 "m3-telescoping-series-3-v1":["partial-gap"],
 "m3-telescoping-series-4-v1":["telescoping-two","partial-sum-limit"],
 "m3-telescoping-series-7-v1":["partial-gap"],
 "m3-telescoping-series-10-v1":["telescoping"],
 "m3-telescoping-series-12-v1":["telescoping-two","partial-sum-limit"],
 "m3-limits-at-infinity-2-v1":["root-square"],
 "m3-limits-at-infinity-6-v1":["root-square"],
 "m3-limits-at-infinity-12-v1":["root-square"],
 "m3-limits-at-infinity-4-v1":["conjugate","root-normalize"],
 "m3-limits-at-infinity-8-v1":["root-square","conjugate"],
 "m3-limits-at-infinity-10-v1":["conjugate","root-normalize"],
 "m3-derivative-definition-ready-1-v1":["input-expression"],
 "m3-derivative-definition-ready-2-v1":["factor-common","cancel-factor"],
 "m3-derivative-definition-practice-1-v1":["difference-quotient"],
 "m3-derivative-definition-practice-2-v1":["difference-quotient"],
 "m3-derivative-definition-practice-5-v1":["cubic-expand","cancel-factor"],
 "m3-function-limits-check-9-v1":["conjugate","cancel-factor"],
 "m3-function-limits-check-20-v1":["fraction-expression","cancel-factor"],
 "m3-function-limits-check-10-v1":["root-square"],
 "m3-function-limits-check-21-v1":["cancel-factor","reciprocal-limit"],
 "m3-sequences-check-11-v1":["partial-sum-limit"],
 "m3-sequences-check-21-v1":[],
 "m3-sequences-check-13-v1":["telescoping","partial-sum-limit"],
 "m3-sequences-check-23-v1":["telescoping","partial-sum-limit"],
 "m3-sequences-check-5-v1":["substitution","sigma"],
 "m3-sequences-check-15-v1":["sum-to-term"],
 "m3-function-limits-check-5-v1":["denominator","factor"],
 "m3-function-limits-check-16-v1":["point","substitution"],
 "m3-function-limits-check-6-v1":["absolute"],
 "m3-function-limits-check-17-v1":["inequality-end"],
 "m3-function-limits-check-12-v1":["log-value"],
 "m3-function-limits-check-23-v1":[],
 "m3-composition-domain-3-v1":["denominator"],
 "m3-composition-domain-4-v1":["root-domain"],
 "m3-composition-domain-5-v1":["root-domain"],
 "m3-composition-domain-6-v1":["denominator"],
 "m3-composition-domain-7-v1":["root-domain","denominator"],
 "m3-composition-domain-8-v1":["root-square"],
 "m3-composition-domain-9-v1":["log"],
 "m3-composition-domain-10-v1":["inequality-end"],
 "m3-composition-domain-11-v1":["denominator","root-domain"],
 "m3-composition-domain-12-v1":["root-domain","inequality-linear"],
 "m3-composition-domain-13-v1":["root-domain","denominator"],
 "m3-composition-domain-14-v1":["denominator"],
 "m3-composition-domain-15-v1":["root-domain","denominator"],
 "m3-composition-domain-16-v1":["inequality-linear"],
};
