// Authored operation-level dependencies. No inference from a page title or word overlap.
// Families not listed here retain their own question-specific worked repair.
export type PrerequisitePlan={lesson:string;families:string[];checks:string[];reason:string};
const r=(lesson:string,families:string,checks:string,reason:string):PrerequisitePlan=>({lesson,families:families.split(" "),checks:checks?checks.split(" "):[],reason});
export const prerequisitePlans:PrerequisitePlan[]=[
 // Junior foundations: terminate at simple operations, never send a learner round a cycle.
 r("jr-signed-product","multiply divide","sign","負号の意味を確認してから積・商へ進む。"),
 r("jr-order-powers","order power","signed-product","累乗を掛け算に戻し、積の符号を確かめる。"),
 r("jr-fractions","add","common-denominator","同じ大きさの単位にそろえてから足す。"),
 r("jr-fractions","divide","","逆数を掛ける意味は、この問題の説明で扱う。"),
 r("jr-ratio-percent","ratio percent","fraction-divide","基準量で割る計算を確かめる。"),
 r("jr-substitution","linear","signed-product","負の数への代入で積の符号を失わない。"),
 r("jr-substitution","square","power","代入する負の数全体を二乗する。"),
 r("jr-like-terms","collect","sign","同じ文字の係数を加減する。"),
 r("jr-like-terms","distribute","signed-product","各項への掛け算の符号を確かめる。"),
 r("jr-monomials","multiply","power signed-product","累乗を掛け算として読む。"),
 r("jr-monomials","divide","fraction-divide power","係数の商と文字の累乗を分ける。"),
 r("jr-expansion","product square","expand collect","一項ずつ掛けて同類項をまとめる。"),
 r("jr-factorization","common","expand","分配法則を逆向きに使う。"),
 r("jr-factorization","product","expand-product","積を展開して係数を確かめる。"),
 r("jr-linear-equation","linear","expand sign","括弧と負号を整理してから両辺を操作する。"),
 r("jr-linear-equation","fraction","common-denominator equation","両辺全体に分母の公倍数を掛ける。"),
 r("jr-simultaneous","eliminate substitute","equation substitution","一つの未知数の式に直して解く。"),
 r("jr-formula-quantities","rearrange","equation","同じ操作を両辺にする。"),
 r("jr-formula-quantities","word","","数量を何で表すかは、この問題で確かめる。"),
 r("jr-square-roots","radical both","power","二乗すると元の数になる値を考える。"),
 r("jr-root-calculation","simplify","root prime","根号の意味と平方数の因数を分けて確かめる。"),
 r("jr-root-calculation","rationalize","root common-denominator","値を変えない分数の変形と根号の積を使う。"),
 r("jr-quadratic-equation","square real-solutions","root power","非負の平方根と方程式の全解を区別する。"),
 r("jr-quadratic-equation","zero-product","zero","与えられた積が零になる条件から全解を求める。"),
 r("jr-quadratic-equation","formula","square-expand root","平方の形を作り、二乗の方程式を解く。"),
 r("jr-coordinates","on-graph","substitution","横の座標を式に入れ、縦の座標と照合する。"),
 r("jr-proportion","direct inverse","point ratio","対応する二量の積または比を使う。"),
 r("jr-linear-function","read slope","coordinates difference","座標と変化量の向きを区別する。"),
 r("jr-quadratic-function","symmetry","power point","負の入力も括弧を付けて二乗する。"),
 r("jr-quadratic-function","rate","slope power","関数値を計算し、変化量の比を取る。"),
 r("jr-angles","triangle","straight-angle","角の和から残る角を求める。"),
 r("jr-similarity","length","ratio","対応する長さの倍率を使う。"),
 r("jr-similarity","area","ratio power","長さの倍率と面積の倍率を分ける。"),
 r("jr-circle-angles","inscribed central","triangle-angle","円の角の関係を、三角形の角と結び付ける。"),
 r("jr-pythagoras","hypotenuse leg","root power","二乗の等式から正の長さを求める。"),
 r("jr-area-volume","area volume","fraction-divide","公式中の分数の計算を確かめる。"),
 r("jr-averages","mean","fraction-divide","合計を個数で割る。"),
 r("jr-frequency-quartiles","relative","fraction-divide","度数を全体の度数で割る。"),
 r("jr-frequency-quartiles","quartile","median","順に並べて半分ずつの中央を見る。"),
 r("jr-probability","count complement","fraction-divide","結果の個数を分数の比で表す。"),
 r("jr-sampling","estimate","ratio","標本の割合を母集団に当てはめる。"),
 // Math I — keep interpretation, conditions and calculation distinct.
 r("m1-real-numbers","finite-decimal repeating-decimal","prime fraction-divide","分母の因数と分数の計算を使う。"),
 r("m1-substitution","integer-substitution","substitution power","負数の代入と累乗の範囲を確かめる。"),
 r("m1-substitution","fraction-substitution fraction-arithmetic","fraction fraction-divide","代入後の分数計算を確かめる。"),
 r("m1-substitution","power-scope order left-to-right","power signed-product","計算の順序と負号の範囲を区別する。"),
 r("m1-like-terms","collect identify","collect","同じ文字の部分をもつ項だけをまとめる。"),
 r("m1-like-terms","brackets sum-product","expand collect","括弧全体に符号や数を掛ける。"),
 r("m1-like-terms","signed subtract-negative","sign","負の数を引く操作を確かめる。"),
 r("m1-distributive-expansion","one two three","expand-product collect","項を漏らさず掛けてからまとめる。"),
 r("m1-product-identities","square conjugates choice common","expand-product","公式を項ごとの掛け算へ戻して確かめる。"),
 r("m1-common-factors","common complete","factor-common","全項に共通する因数を取り出す。"),
 r("m1-quadratic-factorization","monic nonmonic","factor expand-product","因数の積を掛け戻して係数を比べる。"),
 r("m1-grouping","group four","factor-common factor","まとまりを一つの文字のように扱う。"),
 r("m1-square-roots","principal all-roots zero-root real-domain","root","根号が表す一つの値と、平方根全体を分ける。"),
 r("m1-radical-calculation","simplify sum difference","radical collect","根号の中を整理してから同類項をまとめる。"),
 r("m1-radical-calculation","product quotient","root signed-product","根号の積・商を計算し、定義される範囲を残す。"),
 r("m1-rationalizing","single","rationalize-single","分子と分母に同じ非零の数を掛ける。"),
 r("m1-rationalizing","conjugate","conjugate-product rationalize-single","和と差の積で分母の根号を消す。"),
 r("m1-absolute-distance","value distance zero-distance","absolute","数直線上の距離として考える。"),
 r("m1-absolute-distance","interval","absolute inequality-end","距離の条件と境界を対応させる。"),
 r("m1-linear-inequalities","positive negative both-sides brackets","equation expand","両辺操作と、負数で割る場合を分ける。"),
 r("m1-simultaneous-inequalities","overlap empty singleton same-direction","inequality-end set-intersection","両方の不等式に共通する値を残す。"),
 r("m1-simultaneous-inequalities","solve-system","inequality-linear set-intersection","各不等式を解いてから共通範囲を取る。"),
 r("m1-inequality-modeling","budget threshold integer-words","inequality-linear inequality-end","数量の式を作った後、解の境界と整数条件を調べる。"),
 r("m1-set-operations","intersection union complement","set-membership","集合の要素が条件を満たすか一つずつ確かめる。"),
 r("m1-condition-inclusion","subset subset-counter empty-subset","set-membership counterexample","すべての要素が入るか、入らない要素があるかを調べる。"),
 r("m1-condition-inclusion","condition-range range-counter","inequality-end","条件に含まれる境界を落とさない。"),
 r("m1-necessary-sufficient","classify-conditions","implication counterexample","二方向を別々に調べる。"),
 r("m1-condition-negation","compound quantifier","negation counterexample","条件の外側をすべて含める。"),
 r("m1-converse-contrapositive","transform truth-pair","negation implication","否定と命題の向きを別々に変える。"),
 r("m1-direct-proof","parity-algebra consecutive","parity expand-product","整数を文字で表して式を変形する。"),
 r("m1-proof-contrapositive","parity-contra","negation parity","対偶を作り、整数の偶奇を文字で表して証明する。"),
 r("m1-proof-contrapositive","nonzero-contra compound-contra","negation","対偶を作り、非零条件や大小関係を調べる。"),
 r("m1-proof-contradiction","irrational-root","negation parity","有理数と仮定し、互いに素な整数の偶奇との矛盾を導く。"),
 r("m1-proof-contradiction","irrational-expression irrational-reciprocal","","有理数の和差や非零の逆数も有理数になることを専用補足で確認する。"),
 r("m1-function-values","evaluate combine-values","substitution power","関数に入力を代入してから計算する。"),
 r("m1-graph-points","point-membership find-ordinate","point","横と縦の座標を式に入れる。"),
 r("m1-graph-points","coordinate-order","coordinates","座標の順序を読む。"),
 r("m1-domain-range","finite-range interval-range open-range","point inequality-end","入力の範囲と、そこで実現する出力を分ける。"),
 r("m1-basic-parabola","basic-shape opening-width","power point","点を代入して二乗の対称性を見る。"),
 r("m1-parabola-translation","shift-point shift-equation","coordinates point","点の移動と式への代入の向きを区別する。"),
 r("m1-completing-square","integer-completion completion-check","square-expand","展開して増えた定数を補正する。"),
 r("m1-completing-square","fraction-completion","square-expand fraction","分数の係数でも同じ補正をする。"),
 r("m1-completing-square-coefficient","positive-leading negative-leading outer-factor-check","factor-common square","先に二次の係数をくくり、括弧内を平方完成する。"),
 r("m1-quadratic-graph","graph-expanded","square vertex","平方完成して軸と頂点を読む。"),
 r("m1-quadratic-graph","graph-vertex-form vertex-form-reading","vertex","平方が零になる入力を探す。"),
 r("m1-determine-quadratic","vertex-and-point axis-and-points three-points","point equation","通る点を式へ入れて係数の条件を作る。"),
 r("m1-parabola-extrema","vertex-extrema","vertex","与えられた平方の形から頂点と値域を読む。"),
 r("m1-parabola-extrema","complete-extrema","vertex square","平方完成して、二乗の最小値と係数の符号を使う。"),
 r("m1-interval-extrema","axis-inside axis-outside","vertex substitution","頂点が範囲内かを見て、端点の値も比べる。"),
 r("m1-interval-extrema","unattained-endpoint","inequality-end","近づける値と、実際に取る値を区別する。"),
 r("m1-quadratic-factor-equation","factor-equation","factor zero","積の各因数が零になる場合を落とさない。"),
 r("m1-quadratic-factor-equation","square-equation square-zero square-negative","root","二乗の方程式の全解を考える。"),
 r("m1-quadratic-factor-equation","unsafe-division","zero denominator","零かもしれない文字で割らない。"),
 r("m1-quadratic-formula","quadratic-formula formula-no-real formula-double discriminant-count","power root","係数の符号を入れ、根号内の符号を調べる。"),
 r("m1-equation-graph","x-intercepts intercept-count","point discriminant","横軸上では縦の座標が零になる。"),
 r("m1-quadratic-inequality","positive-leading-sign negative-leading-sign","zero inequality-end","零になる点と、その間の符号を分ける。"),
 r("m1-quadratic-inequality-boundaries","tangent-sign no-intersection-sign","vertex inequality-end","零になる点の有無と不等号の境界を確認する。"),
 r("m1-graph-intersections","parabola-line two-parabolas cancel-quadratic","point zero","同じ点が両方の式を満たすことを使う。"),
 r("m1-graph-intersections","no-shared-point","discriminant","共有点の横の座標を求める方程式の実数解を調べる。"),
 r("m1-quadratic-model","rectangle-maximum time-height","vertex inequality-end","数量の意味から定義域を決めて最大値を求める。"),
 r("m1-right-triangle","pythagoras positive-length","distance","直角の向かいの辺と正の長さを使う。"),
 r("m1-trig-meaning","trig-ratios similarity-ratio","triangle-sides similarity","着目する角に対応する辺の比を読む。"),
 r("m1-special-angles","special-ratio derive-special","trig distance","特別な三角形の辺から比を作る。"),
 r("m1-trig-sides-angles","side-from-angle angle-from-ratio trig-approximation","trig equation","比の式を作り、求める量について解く。"),
 r("m1-trig-coordinates","coordinate-ratios endpoint-ratios","trig coordinates","辺の比から座標の比へ広げる。"),
 r("m1-trig-relations","recover-cosine recover-sine tangent-squared","trig root","二乗の式を解いた後、角の範囲で符号を決める。"),
 r("m1-trig-relations","complement-ratio supplement-ratio","trig-coordinate","対応する点の座標の符号を読む。"),
 r("m1-equal-sines","sine-all-angles cosine-unique unit-sine-angle zero-sine-endpoints","trig-coordinate","指定された角の範囲で同じ座標の点を探す。"),
 r("m1-sine-law","sine-pairing sine-side","trig equation","向かい合う辺と角を対応させる。"),
 r("m1-sine-circumcircle","circumradius radius-to-chord","trig equation","比の式から半径または辺を解く。"),
 r("m1-cosine-law-side","cosine-setup cosine-side","trig root","二乗した長さから正の長さを求める。"),
 r("m1-cosine-law-angle","cosine-angle-type cosine-exact-angle","trig equation","三辺から余弦の値を求める。"),
 r("m1-triangle-choice","ssa-candidates ssa-right-candidate ssa-angle-feasibility","trig-coordinate triangle-angle","同じ正弦の候補と三角形としての角の条件を調べる。"),
 r("m1-triangle-area","triangle-area height-and-area area-angle-choice","trig triangle-area","高さを三角比で表す。"),
 r("m1-measurement","survey-height survey-triangle split-plane-area","trig triangle-angle","図を分けて辺と角の対応を作る。"),
 r("m1-space-triangles","cuboid-section pyramid-section","distance trig","必要な平面の直角三角形を取り出す。"),
 r("m1-histogram","class-mean","mean","階級値に度数を掛けて合計を考える。"),
 r("m1-representative-values","arithmetic-mean pooled-mean","mean","平均を単純に平均せず、合計と個数に戻す。"),
 r("m1-representative-values","median","median","値を並べて中央を読む。"),
 r("m1-boxplot","quartiles range-iqr draw-boxplot","median","並べたデータを分けて中央値を取る。"),
 r("m1-data-variance","deviation deviation-variance","mean power","平均からの偏差を作り、二乗して平均する。"),
 r("m1-standard-deviation","standard-deviation","variance root","分散から非負の平方根を取る。"),
 r("m1-standard-deviation","compare-sd","","既知の標準偏差を比べ、散らばりの意味を専用補足で確認する。"),
 r("m1-variance-calculation","variance-moments variance-shift-method","variance square-expand","二乗の平均と平均の二乗を区別する。"),
 r("m1-data-transformation","transformed-mean","mean expand","平均と一次変換の関係を確かめる。"),
 r("m1-data-transformation","transformed-spread","variance absolute","偏差は係数倍、標準偏差は係数の絶対値倍になる。"),
 r("m1-scatterplot","paired-points","coordinates","二つの値を一つの点として読む。"),
 r("m1-correlation-coefficient","correlation-calculation","variance fraction","二種類の偏差と標準偏差を計算する。"),
 r("m1-hypothesis-thinking","simulation-tail simulation-decision","probability","仮定の下で起こる結果の割合を見る。"),
 // Math A — counting models precede probability; proofs/conditions are not algebra drills.
 r("ma-sum-product","sum","","同時に起こらない場合の数を足す理由を専用補足で確認する。"),
 r("ma-sum-product","product","product-count","順に選ぶ各段階の選択肢を掛ける。"),
 r("ma-changing-options","unequal-options even-digits","product-count","各枝に残る選択肢を数える。"),
 r("ma-set-count","union outside","set-intersection","重複して数えた部分を確かめる。"),
 r("ma-permutation","all-permutations partial-permutations","product-count","選ぶたびに残りが減る積を作る。"),
 r("ma-repeated-choice","repeat-code repeat-integer","product-count power","毎回使える個数と先頭の条件を分ける。"),
 r("ma-restricted-permutation","adjacent left-end both-ends","product-count","条件を先に満たすまとまりを作る。"),
 r("ma-circular-permutation","circle labelled-seats","product-count","同じ配置と見なす回転と、区別される席を分ける。"),
 r("ma-combination","combination boundary-combination","product-count","順序による重複を取り除く。"),
 r("ma-order-or-selection","choose-method arrange-method","combination","順序や役割を入れ替えて同じか調べる。"),
 r("ma-identical-permutation","identical paths","combination","同じものの交換による重複を除く。"),
 r("ma-grouping","named-groups unnamed-equal unnamed-unequal","combination","一組ずつ選び、組自体の区別を確かめる。"),
 r("ma-count-complement","at-least nonadjacent","product-count","全体と除く場合を同じ数え方で求める。"),
 r("ma-events","die-event coin-event","set-membership","結果を集合の要素として捉える。"),
 r("ma-equally-likely","color-weight sum-weight","probability","種類ではなく等確率の結果を数える。"),
 r("ma-probability-count","single-count","probability","等確率の全体と該当する結果を数える。"),
 r("ma-probability-count","pair-count","combination probability","同じ単位で分母と分子の組を数える。"),
 r("ma-probability-complement","no-heads zero-one","probability","全体の確率一から除く。"),
 r("ma-probability-union","union disjoint","set-intersection fraction","重なりを二度足さない。"),
 r("ma-probability-tree","tree-path","conditional","一つの経路に沿って条件付き確率を掛ける。"),
 r("ma-probability-tree","tree-union","conditional fraction","枝の確率を掛け、異なる経路の確率を足す。"),
 r("ma-replacement","with-replacement without-replacement","conditional","条件による残りの玉の変化を分母へ反映する。"),
 r("ma-independent-trials","independent-product","probability power","独立な試行の一経路の確率を掛ける。"),
 r("ma-independent-trials","dependence","conditional","前の結果で確率が変わるか調べる。"),
 r("ma-repeated-trials","binomial-probability","combination independence","成功位置の選び方と一経路の確率を分ける。"),
 r("ma-conditional-probability","conditional-denominator","probability","条件を満たす結果だけを全体として数え直す。"),
 r("ma-probability-multiplication","conditional-product conditional-path","conditional","後の段階の確率には前の条件が付く。"),
 r("ma-independent-exclusive","exclusive-dependent","set-intersection independence","排反の積事象零と独立の積の式を区別する。"),
 r("ma-posterior-probability","equal-boxes weighted-boxes","conditional fraction","同じ結果へ至る経路を足して分母を作る。"),
 r("ma-expected-value","two-value-mean three-value-mean","probability fraction","値にそれぞれの確率を掛けて足す。"),
 r("ma-expected-profit","net-profit","expectation sign","受取額の期待値から支払額を引く。"),
 r("ma-figure-angles","triangle-angle crossing-angles","triangle-angle straight-angle","図にある角の関係を式にする。"),
 r("ma-congruence-similarity","correspondence","similarity","対応する頂点の順序で辺をそろえる。"),
 r("ma-parallel-ratios","parallel-length part-whole","similarity ratio","部分と全体の長さを区別する。"),
 r("ma-area-ratios","common-height squared-ratio","triangle-area similarity","同じ高さの場合と相似の場合を分ける。"),
 r("ma-angle-bisector","internal-bisector external-bisector","ratio equation","対応する辺の比から線分を求める。"),
 r("ma-centroid","whole-median part-median","ratio","全体と一部分の比を読み替える。"),
 r("ma-incenter-circumcenter","right-circumcenter","","与えられた斜辺の中点と、斜辺の半分である半径を専用補足で確認する。"),
 r("ma-ceva","ceva-ratio ceva-middle","fraction-divide ratio","辺の比の順序をそろえ、積の等式を解く。"),
 r("ma-menelaus","menelaus-ratio outer-ratio","fraction-divide ratio","外側の線分と辺全体の長さを分ける。"),
 r("ma-inscribed-angle","half-central opposite-arc","circle-angle","同じ弧に対する角かを確かめる。"),
 r("ma-cyclic-quadrilateral","cyclic-angle cyclic-judgment","circle-angle triangle-angle","向かい合う角の和を円周角と結び付ける。"),
 r("ma-circle-tangent","tangent-length","distance","半径と接線が直角になる三角形を使う。"),
 r("ma-tangent-chord","tangent-chord-angle tangent-opposite-ray","circle-angle straight-angle","半直線の向きで補角になる場合を分ける。"),
 r("ma-power-of-point","internal-power external-power tangent-power","equation root","同じ点から測る二つの長さの積を使う。"),
 r("ma-two-circles","circle-contact circle-position","absolute","中心間距離を半径の和・差と比べる。"),
 r("ma-common-tangents","external-common internal-common","distance","直角三角形の一辺が半径の差か和かを決める。"),
 r("ma-construction-division","construct-equal-parts construct-ratio","similarity","平行線でできる相似な三角形を使う。"),
 r("ma-construction-tangents","construct-tangent-at construct-tangent-from","circle-angle","円周角が直角になる位置を利用する。"),
 r("ma-space-angle-distance","space-distance space-projection","distance","垂直な線分の長さを三平方で求める。"),
 r("ma-divisors-primes","positive-divisors prime-judgment","prime","素因数を使って約数を漏れなく調べる。"),
 r("ma-prime-factorization","divisor-count square-completion","prime power","素因数の指数の選択または偶奇を考える。"),
 r("ma-gcd-lcm","gcd-lcm-calculation common-length common-period","prime","各素因数の指数を比べる。"),
 r("ma-parity-proofs","parity-sum parity-product","parity expand-product","偶奇を整数係数の式で表す。"),
 r("ma-remainder-classification","given-remainder-square all-square-remainders consecutive-product","integer-remainder square-expand","余りで分けた式を展開して調べる。"),
 r("ma-divisibility-digits","digit-sum-rule last-two-rule","integer-remainder","位取りを使って倍数の部分と余りを分ける。"),
 r("ma-euclidean-algorithm","euclid-calculation euclid-reason","integer-remainder","商と余りの等式を使って共通の約数を保つ。"),
 r("ma-linear-diophantine","all-integer-solutions no-integer-solutions","integer-remainder equation","整数である条件を保ちながら解く。"),
 r("ma-integer-count-conditions","nonnegative-solutions positive-solutions","inequality-linear inequality-end","整数解のうち個数の条件を満たす範囲を残す。"),
 r("ma-terminating-recurring","finite-criterion recurring-to-fraction","prime equation","既約分数の分母と、循環部分を消す等式を使う。"),
 r("ma-binary-notation","binary-read binary-write binary-add","power integer-remainder","各桁の重みと二で割った余りを使う。"),
 r("ma-coordinates-space","coordinate-plane coordinate-axis","coordinates","各座標がどの方向を表すか読む。"),
 r("ma-mathematics-activities","square-tiling stone-strategy","integer-remainder","共通の長さや一巡する個数に注目する。"),
 // Math B.
 r("mb-sequence-terms","term next","substitution","添字を一般項へ代入する。"),
 r("mb-arithmetic","term recover","substitution difference","番号の差と値の差を区別する。"),
 r("mb-arithmetic-sum","sum","arithmetic-term","先に末項を求める。"),
 r("mb-arithmetic-sum","count","sigma","両端を含む項数を数える。"),
 r("mb-geometric","term ratio","power fraction-divide","公比を掛ける回数と符号を確かめる。"),
 r("mb-geometric-sum","sum","geometric-term sigma","公比倍する前に和の範囲を読む。"),
 r("mb-geometric-sum","one","sigma","同じ数を項数回足す。"),
 r("mb-sigma","expand constant","substitution","添字の値を一つずつ入れる。"),
 r("mb-power-sums","square cube combine","sigma power","二乗した項の和と和全体の二乗を分ける。"),
 r("mb-differences","odd even","sigma arithmetic-term","初項に一つ手前までの差を足す。"),
 r("mb-partial-fractions","adjacent gap","fraction-expression","通分して分子の係数を照合する。"),
 r("mb-telescoping","one","partial sigma","差に直してから端を残す。"),
 r("mb-telescoping","two","partial-gap sigma","間隔に合わせて二項ずつ残す。"),
 r("mb-weighted-geometric","grow decay","geometric-sum sigma","同じ指数の項をそろえて引く。"),
 r("mb-recurrence","add multiply-add","substitution","初項から順に式へ代入する。"),
 r("mb-recurrence-difference","linear odd","sigma arithmetic-term","漸化式の差を初項から足す。"),
 r("mb-affine-recurrence","positive negative","equation geometric-term","一定の値を引いて等比の形を作る。"),
 r("mb-sum-to-term","joins separate","sigma","前後の部分和の差を作り、初項を別に確かめる。"),
 r("mb-induction-identities","sum geometric","sigma expand-product","次の項を加えて帰納法の仮定を使う。"),
 r("mb-induction-properties","divisibility inequality","integer-remainder expand-product","仮定の式を次の番号の式に組み込む。"),
 r("mb-random-variable","point cumulative","probability fraction","各値に対応する確率を読み、必要な値を足す。"),
 r("mb-expectation","mean square","expectation power","二乗する対象を値そのものと区別する。"),
 r("mb-variance","variance sd","expectation variance","期待値からの偏差の二乗を考える。"),
 r("mb-random-transform","mean","expectation expand","値の一次変換を期待値へ反映する。"),
 r("mb-random-transform","spread","variance absolute","分散は係数の二乗倍、標準偏差は絶対値倍。"),
 r("mb-independent-sum","sum dependent","independence variance","独立性が分散の加法に必要かを確認する。"),
 r("mb-binomial-distribution","exact tail","combination binomial-condition","成功位置と一経路の確率を数える。"),
 r("mb-binomial-distribution","moments","expectation variance","成功回数の期待値と分散を使う。"),
 r("mb-continuous-distribution","interval","rectangle-area","密度の高さではなく面積を求める。"),
 r("mb-normal-distribution","middle tail between","density fraction-divide","標準化した区間の面積を読む。"),
 r("mb-distribution-conditions","binomial","binomial-condition","各試行の確率と独立性を確かめる。"),
 r("mb-sampling","target bias","sampling-bias","調査対象と抽出の偏りを分ける。"),
 r("mb-sample-mean","variance error","variance root","個々の値と平均のばらつきを分ける。"),
 r("mb-binomial-normal","probability boundary","standardize binomial-condition","近似条件を確かめ、整数の範囲を連続区間へ直す。"),
 r("mb-mean-interval","known estimated","standard-error standardize","個々の標準偏差ではなく平均の標準誤差を使う。"),
 r("mb-proportion-interval","interval","ratio root","標本比率と標準誤差を求める。"),
 r("mb-proportion-interval","size","root","標本数が四倍になると、その平方根は二倍になることを幅の式に使う。"),
 r("mb-two-sided-test","mean proportion","standardize","仮説の下で標準化し両側の範囲を見る。"),
 r("mb-one-sided-test","upper lower","standardize","対立仮説の向きに対応する片側を調べる。"),
 r("mb-inference-meaning","interval-bias test-sampling","sampling-bias","抽出の偏りと偶然の誤差を分ける。"),
 r("mb-inference-meaning","test-independence","independence","人数ではなく試行の独立性を確認する。"),
 r("mb-compound-growth","simple compound","ratio geometric-term","毎回の基準量が同じか変わるかを分ける。"),
 r("mb-balance-recurrence","saving loan","geometric-term","前期の残高を倍率で増やし、入出金を加減する。"),
 r("mb-data-function","slope predict","slope point","二点の変化量から一次関数を作る。"),
 r("mb-residuals","residual squared","substitution power","観測値と予測値の差を取る。"),
 r("mb-survey-simulation","design","sampling-bias","調べる母集団と抽出方法を合わせる。"),
 r("mb-survey-simulation","frequency","ratio","試行回数を分母にした割合を見る。"),
 // Math C.
 r("mc-vector-components","forward reverse","coordinates difference","終点から始点を引く。"),
 r("mc-vector-sum","add subtract","vector sign","対応する成分の加減をする。"),
 r("mc-vector-scalar","scale parallel","vector signed-product","各成分を同じ倍率にする。"),
 r("mc-vector-length","length","distance","成分を直角二辺として長さを求める。"),
 r("mc-vector-length","unit","distance fraction-divide","非零のベクトルを大きさで割る。"),
 r("mc-vector-dot","components","signed-product","対応する成分の積を足す。"),
 r("mc-vector-dot","cosine","trig","二つの大きさと間の角の余弦を使う。"),
 r("mc-vector-angle","angle endpoint-angle","dot-product trig-coordinate","非零条件を確認して余弦から角を求める。"),
 r("mc-vector-angle","perpendicular","dot-product","非零のベクトルの内積が零か調べる。"),
 r("mc-vector-division","internal external","ratio vector-scale","始点からの変位と内分・外分の比を対応させる。"),
 r("mc-vector-centroid","midpoint centroid","vector-scale mean","位置ベクトルの平均を取る。"),
 r("mc-vector-basis","independent dependent","vector-scale equation","係数比較が使える条件と計算を分ける。"),
 r("mc-vector-intersection","intersection segment","point equation","同じ交点の二つの表示を等しく置く。"),
 r("mc-vector-line","line segment","vector vector-scale","基準点から方向ベクトルの実数倍だけ動く。"),
 r("mc-vector-proof","midline diagonal","vector vector-scale","点の位置を共通の始点から表す。"),
 r("mc-space-coordinates","projection distance","coordinates distance","各軸方向の差を読み、二乗を足す。"),
 r("mc-space-dot","operation dot","vector dot-product","平面の成分計算を三成分へ広げる。"),
 r("mc-space-dot","angle","dot-product trig-coordinate","内積から余弦を求める。"),
 r("mc-space-division","division centroid","ratio vector-scale","各座標に同じ比の式を適用する。"),
 r("mc-space-line-plane","line plane membership","vector-scale point","表現中の同じ媒介変数を各座標で満たすか調べる。"),
 r("mc-space-normal-sphere","normal","dot-product","法線に垂直な変位の内積を零とする。"),
 r("mc-space-normal-sphere","sphere","distance","中心からの距離が一定という条件を使う。"),
 r("mc-complex-point","point conjugate","coordinates sign","実部と虚部を横と縦へ対応させる。"),
 r("mc-complex-distance","translate","vector","差を座標の変化量として読む。"),
 r("mc-complex-distance","distance","distance absolute","複素数の差の絶対値を距離と結び付ける。"),
 r("mc-complex-polar","quadrant axis","trig-coordinate distance","大きさと、点がある象限から角を決める。"),
 r("mc-complex-product","multiply divide","complex-product fraction-divide","積の展開と共役による分母整理を使う。"),
 r("mc-complex-product","polar-product polar-quotient","trig-coordinate","大きさと角の変化を別々に追う。"),
 r("mc-complex-powers","positive negative","exponent radians","大きさの累乗と偏角の整数倍を計算する。"),
 r("mc-complex-roots","positive negative","radians","一周分ずつ異なる角を割り、すべての根を得る。"),
 r("mc-complex-rotation","left right","complex-product vector","中心を原点へ移して回転させ、中心を戻す。"),
 r("mc-complex-locus","circle bisector","distance square-expand","距離の条件を座標の式に直す。"),
 r("mc-complex-angle","angle collinear","complex-product radians","非零の差の商の偏角を読む。"),
 r("mc-parabola","horizontal vertical","distance square-expand","焦点と準線からの距離を等しく置く。"),
 r("mc-ellipse","horizontal vertical","root","長半径・短半径と焦点距離の二乗の関係を使う。"),
 r("mc-hyperbola","horizontal vertical","root","二乗の関係から焦点距離を求める。"),
 r("mc-conic-shift","parabola ellipse","square vertex","平方完成して移動後の中心や頂点を読む。"),
 r("mc-conic-intersection","two none","intersection discriminant","連立して実数解の個数を調べる。"),
 r("mc-conic-tangent","parabola ellipse hyperbola","point equation","接点が曲線上にあることを確かめる。"),
 r("mc-parametric-elimination","line range","equation inequality-end","媒介変数を消しても元の範囲を残す。"),
 r("mc-parametric-ellipse","whole half","trig-identity trig-coordinate","三角関数の恒等式と角の範囲を使う。"),
 r("mc-polar-coordinates","cartesian polar","trig-coordinate distance","半径と角を横・縦の成分へ直す。"),
 r("mc-polar-equation","line circle","trig-coordinate square","座標との関係から軌跡を読む。"),
 r("mc-matrix-table","read sum","","行と列の位置と、同じ場所の量の加法を専用補足で確認する。"),
 r("mc-matrix-product","sales order","","左の行と右の列の対応する成分の積を足す操作を専用補足で確認する。"),
 r("mc-discrete-graph","two-step","product-count","中継点ごとの経路を数えて足す。"),
];
