import {reviewChecks,type ReviewCheck} from "./review-checks";
const m=String.raw;
export type PrerequisiteCheck=ReviewCheck&{
 repair:string;
 requires:string[];
 // A wrong option can identify a more specific prerequisite, not a diagnosis of the learner.
 wrong?:Record<number,string[]>;
 practice?:string[];
};
function p(id:string,title:string,lesson:string,repair:string,requires:string[],prompt:string,options:string[],correct:number,explanation:string,wrong?:Record<number,string[]>):PrerequisiteCheck{
 return {id,title,lesson,repair,requires,prompt,options:options.map(s=>s.replaceAll("\\frac","\\dfrac")),correct,explanation,wrong};
}
const legacy:Record<string,[string,string[]]>={
 "straight-angle":["straight",[]],"standard-error":["error",["root","fraction"]],
 sign:["subtract",[]],power:["power",["signed-product"]],fraction:["add",["common-denominator"]],
 substitution:["linear",["signed-product","sign"]],expand:["distribute",["signed-product"]],
 factor:["product",["expand-product"]],root:["radical",["power"]],radical:["simplify",["root","prime"]],
 equation:["linear",["expand","sign"]],zero:["zero-product",[]],point:["on-graph",["substitution","coordinates"]],
 slope:["slope",["difference","fraction-divide"]],distance:["hypotenuse",["root","power"]],
 ratio:["part-whole",["fraction-divide"]],probability:["count",["fraction-divide"]],mean:["mean",["fraction-divide"]],
 sigma:["expand",["substitution"]],partial:["adjacent",["fraction-expression"]],derivative:["method",["power-derivative","substitution"]],
 chain:["method",["power-derivative"]],integral:["constant",["power-derivative"]],density:["interval",["rectangle-area"]],
 vector:["forward",["difference","coordinates"]],negation:["boundary",["inequality-end"]],
 trig:["trig-ratios",["triangle-sides","fraction-divide"]],log:["positive",["inequality-end"]],
 exponent:["reciprocal",["power","fraction-divide"]],square:["integer-completion",["square-expand"]]
};
export const prerequisiteChecks:PrerequisiteCheck[]=[
 ...reviewChecks.map(c=>({...c,repair:legacy[c.id][0],requires:legacy[c.id][1]})),
 p("signed-product","掛け算の符号","jr-signed-product","multiply",[],
  "$(-2)\\times(-3)$ はどれですか。",["$-6$","$6$","$-5$"],1,"負の数どうしの積は正です。大きさは $2\\times3=6$ なので $6$。"),
 p("common-denominator","分母をそろえる","jr-fractions","add",[],
  m`$\frac13$ と同じ値で、分母が $12$ の分数はどれですか。`,[m`$\frac1{12}$`,m`$\frac4{12}$`,m`$\frac3{12}$`],1,m`分母を $4$ 倍したので、分子も $4$ 倍します。$\frac13=\frac{1\cdot4}{3\cdot4}=\frac4{12}$。`),
 p("fraction-divide","分数で割る","jr-fractions","divide",[],
  m`$\frac23\div\frac45$ はどれですか。`,[m`$\frac8{15}$`,m`$\frac56$`,m`$\frac65$`],1,m`割る数の逆数を掛けます。$\frac23\cdot\frac54=\frac56$。割る数は零ではありません。`),
 p("prime","平方数の因数を探す","jr-prime-factors","prime",[],
  "$12$ を素因数の積で表したものはどれですか。",["$2\\cdot6$","$2^2\\cdot3$","$2\\cdot3^2$"],1,"$12=2\\cdot2\\cdot3=2^2\\cdot3$。$6$ はまだ $2\\cdot3$ に分けられます。"),
 p("collect","同類項をまとめる","jr-like-terms","collect",["sign"],
  "$3x-2x+4$ を簡単にするとどれですか。",["$5x$","$x+4$","$5x+4$"],1,"$x$ の項どうしの係数を計算します。$(3-2)x+4=x+4$。定数の $4$ は $x$ の項とはまとめません。"),
 p("expand-product","括弧どうしの積","jr-expansion","product",["expand","collect"],
  "$(x+2)(x+3)$ の展開はどれですか。",["$x^2+6$","$x^2+5x+6$","$2x+5$"],1,"各項を掛けて $x^2+3x+2x+6=x^2+5x+6$。"),
 p("square-expand","二乗の展開","jr-expansion","square",["expand-product"],
  "$(x+2)^2$ の展開はどれですか。",["$x^2+4$","$x^2+2x+4$","$x^2+4x+4$"],2,"$(x+2)(x+2)$ を展開します。二つの $2x$ を足すので、中間の項は $4x$ です。"),
 p("conjugate-product","和と差の積","m1-product-identities","conjugates",["expand-product"],
  m`$(\sqrt5+2)(\sqrt5-2)$ はどれですか。`,["$1$","$9$",m`$\sqrt5-4$`],0,m`$(a+b)(a-b)=a^2-b^2$ です。$(\sqrt5)^2-2^2=5-4=1$。`,{2:["root-squared"],1:["expand-product"]}),
 p("rationalize-single","一つの根号を含む分母","jr-root-calculation","rationalize",["root","common-denominator"],
  m`$\frac1{\sqrt3}$ と等しいものはどれですか。`,[m`$\frac{\sqrt3}3$`,m`$\sqrt3$`,m`$\frac13$`],0,m`分子・分母に同じ非零の $\sqrt3$ を掛けます。$\frac1{\sqrt3}=\frac{\sqrt3}{3}$。`),
 p("conjugate","根号の和・差の有理化","m1-rationalizing","conjugate",["conjugate-product","rationalize-single"],
  m`$\frac1{\sqrt5-2}$ を有理化する最初の変形はどれですか。`,[
   m`$\frac{\sqrt5+2}{(\sqrt5-2)(\sqrt5+2)}$`,m`$\frac1{(\sqrt5-2)(\sqrt5+2)}$`,m`$\frac{\sqrt5-2}{5-4}$`
  ],0,m`分子と分母の両方に $\sqrt5+2$ を掛けます。分子も和に変わり、$\sqrt5-2$ をそのまま残すのではありません。積は $5-4=1$、答えは $\sqrt5+2$。元の分母も掛ける数も零ではありません。`,{1:["rationalize-single"],2:["rationalize-single","conjugate-product"]}),
 p("root-square","根号から二乗を取り出す","m1-square-roots","principal",["root","power"],
  m`$x=-3$ のとき、$\sqrt{x^2}$ はどれですか。`,["$-3$","$3$",m`$\pm3$`],1,m`$\sqrt{x^2}=|x|$ です。平方根の記号は非負の値を表すため、$x$ が負なら $-x$ になります。`),
 p("factor-common","共通因数を取り出す","m1-common-factors","common",["expand"],
  "$3x^2+6x$ の因数分解はどれですか。",["$3x(x+2)$","$3x(x+6)$","$3(x+2)$"],0,"どちらの項にも $3x$ があります。$3x\\cdot x+3x\\cdot2=3x(x+2)$。"),
 p("cancel-factor","約分できる部分","rational","factors",["factor-common"],
  m`$x\ne0$ で $\frac{x+2}{x}$ を $1+2$ としてよいですか。`,["よい。上下に $x$ があるから","いけない。分子全体が $x$ の倍数の形ではないから"],1,m`約分は分子全体と分母全体を同じ非零の因数で割ることです。$\frac{x+2}{x}=1+\frac2x$。`),
 p("fraction-expression","分数式の通分","rational-sum","common",["fraction","expand"],
  m`$x\ne0,-1$ で $\frac1x-\frac1{x+1}$ を通分した分子はどれですか。分母を $x(x+1)$ にそろえます。`,["$(x+1)-x$","$x-(x+1)$","$1-1$"],0,m`最初の分子には $x+1$、後の分子には $x$ を掛けます。分子は $(x+1)-x=1$ です。`),
 p("denominator","元の分母の条件","rational","domain",["zero"],
  m`$\frac{x^2-1}{x-1}$ で使えない値はどれですか。`,["使えない値はない","$x=1$","$x=-1$"],1,m`元の分母が零になる $x=1$ は使えません。約分後の $x+1$ に $1$ を入れられても、元の式の条件は変わりません。`),
 p("inequality-end","不等式に境界を含むか","m1-linear-inequalities","endpoints",[],
  m`$x<3$ に $x=3$ は含まれますか。`,["含まれる","含まれない"],1,m`$<$ は等しい場合を含みません。$x\leqq3$ なら $3$ も含みます。`),
 p("inequality-linear","負の数で割る不等式","m1-linear-inequalities","negative",["equation"],
  "$-2x<6$ の解はどれですか。",["$x<-3$","$x>-3$","$x>3$"],1,"両辺を負の数 $-2$ で割ると、不等号の向きが逆になります。$x>-3$。"),
 p("coordinates","座標の順序","jr-coordinates","read",[],
  "点 $(-2,3)$ の横の座標と縦の座標は、順にどれですか。",["$3,-2$","$-2,3$","$2,-3$"],1,"最初が横の座標、次が縦の座標です。符号も含めて読み取ります。"),
 p("difference","変化量の向き","average-rate","change",["sign"],
  "値が $-2$ から $3$ へ変わりました。「後の値から前の値を引く」とどれですか。",["$3-(-2)=5$","$-2-3=-5$","$3-2=1$"],0,"後の値 $3$ から前の値 $-2$ を引きます。順序と負号の両方を確かめます。"),
 p("vertex","平方の形と頂点","m1-completing-square","vertex-reading",["power","equation"],
  "$y=(x-2)^2+3$ の頂点はどれですか。",["$(-2,3)$","$(2,3)$","$(2,-3)$"],1,"二乗が零になるのは $x=2$。そのとき $y=3$ なので頂点は $(2,3)$。"),
 p("quadratic-solve","二次方程式の解の公式","m1-quadratic-formula","quadratic-formula",["power","root"],
  "$x^2-2x-1=0$ の解はどれですか。",[m`$1\pm\sqrt2$`,m`$-1\pm\sqrt2$`,"$1$"],0,m`$a=1,b=-2,c=-1$ です。$x=\frac{2\pm\sqrt{(-2)^2-4(1)(-1)}}2=1\pm\sqrt2$。`),
 p("discriminant","実数解の個数","m1-quadratic-formula","discriminant-count",["power"],
  "$x^2+1=0$ の実数解はいくつですか。",["二つ","一つ","ない"],2,"実数の二乗は非負なので $x^2=-1$ は不可能です。判別式も $-4<0$ になります。"),
 p("intersection","共有点で満たす二つの式","m1-graph-intersections","parabola-line",["point"],
  "$y=x^2$ と $y=x+2$ の共有点の横の座標を求める式はどれですか。",["$x^2=x+2$","$x^2+x+2=0$","$x=x+2$"],0,"共有点では同じ $x$ に対して $y$ が等しいので、右辺どうしを等しくします。"),
 p("triangle-sides","着目する角と斜辺","m1-right-triangle","side-roles",[],
  "直角三角形の斜辺はどの辺ですか。",["図で下に描かれた辺","直角の向かいにある辺","着目する鋭角の向かいの辺"],1,"斜辺は直角の向かいです。図を回転させても変わりません。"),
 p("triangle-angle","三角形の内角の和","jr-angles","triangle",["straight-angle"],
  m`三角形の二つの角が $50^\circ,60^\circ$ です。残る角はどれですか。`,[m`$70^\circ$`,m`$110^\circ$`,m`$250^\circ$`],0,m`内角の和は $180^\circ$。$180^\circ-50^\circ-60^\circ=70^\circ$。`),
 p("similarity","相似で対応する辺","jr-similarity","length",["ratio"],
  "相似な二つの三角形で、対応する辺の長さが小さい方 $2$、大きい方 $6$ です。小さい方の別の辺が $4$ なら、対応する大きい方の辺はどれですか。",["$8$","$12$","$24$"],1,"長さの倍率は $6\\div2=3$。対応する辺を $4\\times3=12$ とします。"),
 p("triangle-area","面積と底辺・高さ","jr-area-volume","area",[],
  "底辺 $6$、高さ $4$ の三角形の面積はどれですか。",["$24$","$12$","$10$"],1,m`底辺と、それに垂直な高さを使って $\frac{6\cdot4}{2}=12$ です。`),
 p("circle-angle","円周角と中心角","jr-circle-angles","inscribed",["triangle-angle"],
  m`同じ弧に対する中心角が $100^\circ$ です。円周角はどれですか。`,[m`$50^\circ$`,m`$100^\circ$`,m`$200^\circ$`],0,m`同じ弧に対する円周角は中心角の半分なので $50^\circ$。`),
 p("trig-coordinate","座標から三角関数へ","trig-unit-circle","coordinate",["coordinates","trig"],
  m`単位円上の点が $(\cos\theta,\sin\theta)$ です。$\sin\theta$ はどの座標ですか。`,["横の座標","縦の座標","横と縦の座標の和"],1,"単位円では縦の座標が正弦、横の座標が余弦です。"),
 p("radians","弧度法の単位","trig-radians","conversion",["fraction-divide"],
  m`$180^\circ$ は何ラジアンですか。`,[m`$\pi$`,m`$2\pi$`,m`$\frac\pi2$`],0,m`一周 $360^\circ$ が $2\pi$ ラジアンなので、半周は $\pi$ ラジアンです。`),
 p("trig-identity","三角関数の二乗の関係","trig-identities","recover",["trig-coordinate","fraction"],
  m`$\sin\theta=\frac35$ のとき、$\cos^2\theta$ はどれですか。`,[m`$\frac25$`,m`$\frac45$`,m`$\frac{16}{25}$`],2,m`$\sin^2\theta+\cos^2\theta=1$ より $1-\frac9{25}=\frac{16}{25}$。$\cos\theta$ の符号を決めるには角の範囲も必要です。`),
 p("log-value","対数を指数へ読み替える","logarithm-meaning","translate",["power"],
  "$\\log_2 8$ の値はどれですか。",["$3$","$4$","$16$"],0,"$2$ を何乗すると $8$ になるかを考えます。$2^3=8$ なので $\\log_2 8=3$。"),
 p("log-product","対数の積と和","logarithm-laws","combine",["log-value"],
  m`$a>0,\ a\ne1,\ M>0,\ N>0$ のとき、$\log_a(MN)$ はどれですか。`,[m`$\log_a M+\log_a N$`,m`$(\log_a M)(\log_a N)$`,m`$\log_a(M+N)$`],0,"真数の積が、対数の和になります。底と真数の条件を満たすときに使います。"),
 p("set-membership","集合に入る条件","m1-sets-elements","membership",[],
  m`$A=\{1,3,5\}$ に $2$ は含まれますか。`,["含まれる","含まれない"],1,"書かれた要素は $1,3,5$ です。$1$ と $3$ の間の数がすべて入るという意味ではありません。"),
 p("set-intersection","両方に入る要素","m1-set-operations","intersection",["set-membership"],
  m`$A=\{1,2\},B=\{2,3\}$ の共通部分はどれですか。`,[m`$\{1,2,3\}$`,m`$\{2\}$`,m`$\{1,3\}$`],1,"両方に含まれる要素だけを残します。$2$ だけです。"),
 p("counterexample","反例の条件","m1-statements-counterexamples","counterexample",["substitution"],
  "「すべての整数 $n$ で $n^2>0$」が誤りと分かる反例はどれですか。",["$n=1$","$n=-1$","$n=0$"],2,"$n=0$ は整数ですが $n^2=0$ で結論を満たしません。一つの反例で「すべて」という主張を否定できます。"),
 p("implication","条件から結論への向き","m1-necessary-sufficient","direction-name",["set-membership"],
  "「$4$ の倍数ならば $2$ の倍数」は正しい命題です。「$4$ の倍数である」は「$2$ の倍数である」ための何条件ですか。",["十分条件","必要条件だが十分条件ではない"],0,"$4$ の倍数であると分かれば、必ず $2$ の倍数と言えます。この向きが十分条件です。"),
 p("product-count","段階ごとに数える","ma-sum-product","product",[],
  "上着 $2$ 種類、ズボン $3$ 種類からそれぞれ一つ選びます。どの組合せも使えるとき、選び方は何通りですか。",["$5$","$6$","$9$"],1,"上着一つにつきズボンは $3$ 通りなので、$3+3=2\\times3=6$ 通りです。"),
 p("combination","選ぶことと並べること","ma-combination","combination",["product-count"],
  "区別できる $4$ 人から係を $2$ 人選びます。二人に役割の違いはありません。選び方は何通りですか。",["$12$","$6$","$8$"],1,m`順に選ぶと $4\cdot3=12$ 通りですが、同じ二人を二度数えるので $\frac{12}{2}=6={}_4C_2$ 通り。`),
 p("complement","起こらない側の確率","ma-probability-complement","no-heads",["probability"],
  m`ある事象が起こる確率は $\frac3{10}$ です。起こらない確率はどれですか。`,[m`$\frac7{10}$`,m`$\frac3{10}$`,m`$\frac1{10}$`],0,m`起こる場合と起こらない場合で全体なので、$1-\frac3{10}=\frac7{10}$。`),
 p("conditional","条件を満たすものを分母にする","ma-conditional-probability","conditional-denominator",["probability"],
  "公平なさいころの目が偶数だと分かりました。出た目が $6$ である確率はどれですか。",[m`$\frac16$`,m`$\frac13$`,m`$\frac12$`],1,m`条件を満たす目は $2,4,6$。その三つが同じ確率で、該当するのは一つなので $\frac13$。`),
 p("independence","独立を確かめる等式","ma-independent-exclusive","independence-identity",[],
  m`$P(A)=\frac12,\ P(B)=\frac12,\ P(A\cap B)=\frac14$ のとき、$A,B$ は独立ですか。`,["独立である","独立ではない"],0,m`$P(A\cap B)=P(A)P(B)=\frac14$ なので独立です。排反かどうかとは別の条件です。`),
 p("expectation","値に確率を掛けて足す","ma-expected-value","two-value-mean",["probability","fraction"],
  m`$0$ 点と $6$ 点が、それぞれ確率 $\frac23,\frac13$ で得られます。期待値はどれですか。`,["$3$","$2$","$6$"],1,m`$0\cdot\frac23+6\cdot\frac13=2$。二種類の点数を単純に平均するのではありません。`),
 p("variance","平均からのずれを二乗する","m1-data-variance","deviation-variance",["mean","power"],
  "$1,3$ の分散はどれですか。",["$0$","$1$","$2$"],1,m`平均は $2$。分散は $\frac{(1-2)^2+(3-2)^2}{2}=1$ です。偏差を二乗せずに足すと零になります。`),
 p("median","並べたデータの中央","jr-averages","median",[],
  "$2,9,4$ の中央値はどれですか。",["$9$","$5$","$4$"],2,"小さい順に $2,4,9$ と並べます。真ん中は $4$ です。"),
 p("sampling-bias","調べたい集団と調べた人","jr-sampling","bias",[],
  "全校生徒の平均通学時間を知りたいとき、偏りを避ける選び方はどちらですか。",["早朝に登校した人だけを調べる","全校生徒の名簿から無作為に選ぶ"],1,"通学時間と関係しそうな登校時刻で選ぶと、全校を代表しない可能性があります。人数を増やすだけではその偏りは除けません。"),
 p("standardize","標準化で引く量・割る量","mb-normal-distribution","middle",["mean","fraction-divide"],
  "平均 $50$、標準偏差 $10$ の正規分布に従う値 $60$ を標準化するとどれですか。",["$1$","$6$","$10$"],0,m`平均を引いて、標準偏差で割ります。$z=\frac{60-50}{10}=1$。分散で割るのではありません。`),
 p("arithmetic-term","初項から何回足すか","mb-arithmetic","term",["substitution"],
  "初項 $3$、公差 $2$ の等差数列の第 $n$ 項はどれですか。",["$3+2n$","$3+2(n-1)$","$3\\cdot2^{n-1}$"],1,"第 $1$ 項ではまだ公差を足しません。第 $n$ 項までは $n-1$ 回足すので $3+2(n-1)$。"),
 p("geometric-term","等比数列の一般項","mb-geometric","term",["power"],
  "初項 $3$、公比 $2$ の等比数列の第 $n$ 項はどれですか。",["$3+2(n-1)$","$3\\cdot2^n$","$3\\cdot2^{n-1}$"],2,"初項から $2$ を $n-1$ 回掛けます。$n=1$ を代入すると初項 $3$ に戻ります。"),
 p("geometric-sum","有限個の等比数列の和","mb-geometric-sum","sum",["geometric-term","sigma"],
  m`$n$ は正の整数、$r\ne1$ です。$1+r+\cdots+r^{n-1}$ はどれですか。`,[m`$\frac{1-r^n}{1-r}$`,m`$\frac1{1-r}$`,m`$\frac{1-r^{n-1}}{1-r}$`],0,m`和を $S$ と置くと $S-rS=1-r^n$。項数は $n$ です。有限和なので $r^n$ の項を残します。`),
 p("telescoping","消えずに残る項","mb-telescoping","one",["sigma","fraction"],
  m`$\sum_{k=1}^{3}\left(\frac1k-\frac1{k+1}\right)$ はどれですか。`,[m`$0$`,m`$1-\frac14$`,m`$1-\frac13$`],1,m`$(1-\frac12)+(\frac12-\frac13)+(\frac13-\frac14)$ と書くと、最初の $1$ と最後の $-\frac14$ が残ります。`),
 p("sum-to-term","部分和から一項を取り出す","mb-sum-to-term","joins",["sigma"],
  "$S_n=a_1+\\cdots+a_n$ のとき、$n\\geqq2$ で $a_n$ に等しい式はどれですか。",["$S_n-S_{n-1}$","$S_n-S_{n+1}$","$S_n\\div n$"],0,"直前までの和を引けば最後の一項だけが残ります。初項は別に $a_1=S_1$ で確かめます。"),
 p("power-derivative","累乗の微分","polynomial-differentiation","power-rule",[],
  "$x^3$ の導関数はどれですか。",["$3x^2$","$x^2$","$3x^3$"],0,"指数 $3$ を係数に掛け、指数を一つ下げます。$(x^3)'=3x^2$。"),
 p("product-derivative","積の微分の二つの項","m3-product-derivative","method",["power-derivative"],
  m`$u(x),v(x)$ が微分可能なとき、$(uv)'$ はどれですか。`,["$u'v'$","$u'v+uv'$","$u'+v'$"],1,"片方を微分してもう片方を残す項を、両方について作って足します。"),
 p("derivative-sign","導関数の符号と増減","derivative-sign","sign-meaning",[],
  "$f'(x)>0$ がある区間で常に成り立つとき、その区間で $f$ はどうなりますか。",["増加する","減少する","常に正の値をとる"],0,"導関数の正負は増え方・減り方を表します。関数値そのものの正負ではありません。"),
 p("endpoint-value","原始関数の両端の差","definite-integrals","bounds",["substitution","difference"],
  m`$F(x)=x^2$ は $2x$ の原始関数です。$\int_1^3 2x\,dx$ はどれですか。`,["$F(3)-F(1)=8$","$F(1)-F(3)=-8$","$F(3)=9$"],0,"上端の値から下端の値を引きます。$3^2-1^2=8$。"),
 p("dot-product","成分から内積へ","mc-vector-dot","components",["signed-product"],
  m`$\vec a=(1,2),\vec b=(3,-1)$ の内積はどれですか。`,["$1$","$(3,-2)$","$5$"],0,m`対応する成分の積を足します。$\vec a\cdot\vec b=1\cdot3+2(-1)=1$。内積は数です。`),
 p("complex-product","虚数単位の二乗","complex-arithmetic","i-square",["expand-product"],
  "$(1+i)(1-i)$ はどれですか。",["$0$","$2$","$1-i$"],1,"$1-i^2=1-(-1)=2$。$i^2=-1$ を使います。"),
 p("absolute","絶対値と距離","m1-absolute-distance","value",[],
  "$|-3|$ はどれですか。",["$-3$","$3$",m`$\pm3$`],1,"絶対値は数直線上で原点からの距離です。距離は負にならないので $3$。"),
 p("root-quotient","根号の商","m1-radical-calculation","quotient",["root"],
  m`$a\geqq0,\ b>0$ のとき、$\frac{\sqrt a}{\sqrt b}$ はどれですか。`,[m`$\sqrt{\frac ab}$`,m`$\sqrt{a-b}$`,m`$\frac ab$`],0,m`根号の積・商の性質より $\frac{\sqrt a}{\sqrt b}=\sqrt{\frac ab}$。分母側は正でなければなりません。`),
 p("root-normalize","根号を含む数列の式整理","m3-sequence-radical-limit","scale",["root-quotient","root-square"],
  m`$n$ は正の整数です。$\frac{\sqrt{n^2+n}}n$ と等しい式はどれですか。`,[m`$\sqrt{1+\frac1n}$`,m`$\sqrt{1+n}$`,m`$1+\frac1n$`],0,m`$n>0$ より $n=\sqrt{n^2}$。根号の中では $n^2$ で割り、$\sqrt{\frac{n^2+n}{n^2}}=\sqrt{1+\frac1n}$ です。`,{1:["root-quotient"],2:["root-quotient","root-squared"]}),
 p("reciprocal-limit","逆数の数列の極限","m3-sequence-convergence","limit",[],
  m`$n$ が正の整数を動くとき、$\lim_{n\to\infty}\frac1n$ はどれですか。`,["$0$","$1$","極限をもたない"],0,m`$n$ が大きくなるほど $\frac1n$ は正のまま零に近づきます。どの項も零でなくても、極限値は零になります。`),
 p("partial-gap","因数の間隔と部分分数","mb-partial-fractions","gap",["fraction-expression"],
  m`$k$ は正の整数です。$\frac1{k(k+2)}$ はどれですか。`,[m`$\frac1k-\frac1{k+2}$`,m`$\frac12\left(\frac1k-\frac1{k+2}\right)$`,m`$2\left(\frac1k-\frac1{k+2}\right)$`],1,m`通分すると $\frac1k-\frac1{k+2}=\frac2{k(k+2)}$。元の分子は $1$ なので半分にします。`),
 p("telescoping-two","二つずれた和の両端","mb-telescoping","two",["sigma","fraction"],
  m`$\sum_{k=1}^3\left(\frac1k-\frac1{k+2}\right)$ はどれですか。`,[m`$1-\frac15$`,m`$1+\frac12-\frac14-\frac15$`,m`$0$`],1,m`$(1-\frac13)+(\frac12-\frac14)+(\frac13-\frac15)$。正負で同じ分母の項だけを消すので、両端に二項ずつ残ります。`),
 p("partial-sum-limit","無限級数は何の極限か","m3-infinite-series-meaning","partial",["sigma"],
  m`$\sum_{n=1}^{\infty}a_n$ の和は、何の極限として考えますか。`,["一般項 $a_n$ の極限","部分和 $a_1+\\cdots+a_N$ の $N\\to\\infty$ の極限","最後の項"],1,"有限個まで足した部分和の極限を調べます。一般項が零に近づくことだけでは、和の収束は決まりません。"),
 p("input-expression","式全体を代入する","m3-function-input","expression",["substitution"],
  "$f(t)=t^2+t$ のとき、$f(x+h)$ を計算する式はどれですか。",["$(x+h)^2+(x+h)$","$x^2+x+h$","$f(x)+f(h)$"],0,"もとの式の $t$ をすべて $x+h$ に置き換えます。代入する式を括弧で囲みます。"),
 p("cubic-expand","三乗を展開する","cubic-expansion","binomial-cube",["expand-product","square-expand"],
  "$(x+h)^3-x^3$ はどれですか。",["$h^3$","$3x^2h+3xh^2+h^3$","$3x^2h+h^3$"],1,"$(x+h)^2(x+h)$ を展開すると $x^3+3x^2h+3xh^2+h^3$。$x^3$ だけが引き算で消えます。"),
 p("difference-quotient","差商で割る量","m3-derivative-meaning","method",["difference","fraction-divide"],
  "入力が $x$ から $x+h$ に変わったとき（$h\\ne0$）、平均変化率はどれですか。",[m`$\frac{f(x+h)-f(x)}h$`,m`$\frac{f(x+h)}h$`,m`$f(x+h)-f(x)$`],0,m`出力の変化量 $f(x+h)-f(x)$ を、入力の変化量 $(x+h)-x=h$ で割ります。`),
 p("trig-double","二倍角から二乗を直す","trig-double-half","double-angle",["trig-identity"],
  m`$\sin^2 x$ と等しい式はどれですか。`,[m`$\frac{1-\cos 2x}{2}$`,m`$\frac{1+\cos 2x}{2}$`,m`$\frac{\sin 2x}{2}$`],0,m`$\cos 2x=1-2\sin^2x$ を変形します。$\sin^2x=\frac{1-\cos2x}{2}$。`),
 p("vector-scale","成分の実数倍","mc-vector-scalar","scale",["signed-product"],
  "$-2(1,-3)$ はどれですか。",["$(-2,6)$","$(-2,-3)$","$(-2,-6)$"],0,"両方の成分に $-2$ を掛けます。$(-2\\cdot1,(-2)(-3))=(-2,6)$。"),
 p("integer-remainder","商と余りの範囲","ma-quotient-remainder","negative-remainder",["equation"],
  "$-7$ を $3$ で割った商と余りはどれですか。余りは $0$ 以上 $3$ 未満とします。",["商 $-2$、余り $-1$","商 $-3$、余り $2$","商 $-3$、余り $-2$"],1,"$-7=3\\cdot(-3)+2$。余りは $0\\leqq2<3$ を満たします。"),
 p("parity","偶数・奇数の文字による表示","m1-direct-proof","parity-algebra",[],
  "奇数を表す式はどれですか。$k$ は整数とします。",["$2k$","$2k+1$","$k+1$"],1,"奇数は $2$ で割ると余り $1$ になるので、$2k+1$ と表せます。$k+1$ は偶数にもなります。"),
 p("binomial-condition","反復試行の条件","ma-repeated-trials","binomial-condition",["independence"],
  "成功確率が毎回同じ $p$ の試行を $n$ 回行います。二項分布を使うには、さらに何が必要ですか。",["各試行が独立であること","成功と失敗の回数が同じこと","$p$ が必ず半分であること"],0,"各試行の独立性も必要です。確率が同じという条件だけでは二項分布とは限りません。"),
 p("distance-sign","二点間の距離と符号","m1-absolute-distance","two-points",["absolute"],
  "数直線上の二点 $2,-1$ の間の距離はどれですか。",["$-3$","$3$","$1$"],1,"座標の差は $-1-2=-3$ ですが、二点間の距離はその絶対値 $|-1-2|=3$ です。"),
 p("root-domain","根号の中が満たす条件","m1-square-roots","real-domain",["root","inequality-end"],
  m`$\sqrt{x-2}$ が実数として定義される条件はどれですか。`,[m`$x>2$`,m`$x\geqq2$`,m`$x\ne2$`],1,m`根号の中が非負、つまり $x-2\geqq0$ なので $x\geqq2$。$\sqrt0=0$ も定義されています。`),
 p("root-squared","根号を二乗する","jr-square-roots","squared",["root"],
  m`$(\sqrt5)^2$ はどれですか。`,["$5$",m`$\sqrt5$`,"$25$"],0,m`$\sqrt5$ は二乗すると $5$ になる非負の数です。したがって $(\sqrt5)^2=5$。`),
 p("rectangle-area","長方形の面積","jr-area-volume","rectangle",[],
  "横の長さ $3$、縦の長さ $2$ の長方形の面積はどれですか。",["$5$","$6$","$3$"],1,"縦と横の長さを掛けるので $3\\times2=6$。三角形ではないので半分にしません。"),
];
// Where the destination has only broader exercises, use its focused worked check instead
// of presenting a different operation as equivalent practice.
const noBroaderPractice=["signed-product","ratio","difference","cubic-expand","trig-double","parity","root-squared","rectangle-area","distance-sign"];
for(const id of noBroaderPractice)prerequisiteChecks.find(c=>c.id===id)!.practice=[];
const derivative=prerequisiteChecks.find(c=>c.id==="derivative")!;
derivative.practice=["m3-derivative-meaning-practice-3-v1","m3-derivative-meaning-practice-5-v1","m3-derivative-meaning-practice-6-v1"];
derivative.wrong={2:["substitution"]};
prerequisiteChecks.find(c=>c.id==="difference-quotient")!.practice=["m3-derivative-meaning-practice-1-v1","m3-derivative-meaning-practice-2-v1","m3-derivative-meaning-practice-4-v1"];
prerequisiteChecks.find(c=>c.id==="cancel-factor")!.practice=["r-practice-5-v1"];
prerequisiteChecks.find(c=>c.id==="chain")!.wrong={2:["input-expression"]};
export const prerequisiteById=new Map(prerequisiteChecks.map(c=>[c.id,c]));
export function prerequisitesOf(c:PrerequisiteCheck,choice:number|null):PrerequisiteCheck[]{
 const ids=choice!==null&&c.wrong?.[choice]?c.wrong[choice]:c.requires;
 return ids.map(id=>prerequisiteById.get(id)!).filter(Boolean);
}
